################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/src/USER-OMP/angle_charmm_omp.cpp \
../lammps-dev/src/USER-OMP/angle_class2_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_delta_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_periodic_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_shift_exp_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_shift_omp.cpp \
../lammps-dev/src/USER-OMP/angle_cosine_squared_omp.cpp \
../lammps-dev/src/USER-OMP/angle_dipole_omp.cpp \
../lammps-dev/src/USER-OMP/angle_fourier_omp.cpp \
../lammps-dev/src/USER-OMP/angle_fourier_simple_omp.cpp \
../lammps-dev/src/USER-OMP/angle_harmonic_omp.cpp \
../lammps-dev/src/USER-OMP/angle_quartic_omp.cpp \
../lammps-dev/src/USER-OMP/angle_sdk_omp.cpp \
../lammps-dev/src/USER-OMP/angle_table_omp.cpp \
../lammps-dev/src/USER-OMP/bond_class2_omp.cpp \
../lammps-dev/src/USER-OMP/bond_fene_expand_omp.cpp \
../lammps-dev/src/USER-OMP/bond_fene_omp.cpp \
../lammps-dev/src/USER-OMP/bond_gromos_omp.cpp \
../lammps-dev/src/USER-OMP/bond_harmonic_omp.cpp \
../lammps-dev/src/USER-OMP/bond_harmonic_shift_cut_omp.cpp \
../lammps-dev/src/USER-OMP/bond_harmonic_shift_omp.cpp \
../lammps-dev/src/USER-OMP/bond_morse_omp.cpp \
../lammps-dev/src/USER-OMP/bond_nonlinear_omp.cpp \
../lammps-dev/src/USER-OMP/bond_quartic_omp.cpp \
../lammps-dev/src/USER-OMP/bond_table_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_charmm_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_class2_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_cosine_shift_exp_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_fourier_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_harmonic_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_helix_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_multi_harmonic_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_nharmonic_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_opls_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_quadratic_omp.cpp \
../lammps-dev/src/USER-OMP/dihedral_table_omp.cpp \
../lammps-dev/src/USER-OMP/domain_omp.cpp \
../lammps-dev/src/USER-OMP/ewald_omp.cpp \
../lammps-dev/src/USER-OMP/fix_gravity_omp.cpp \
../lammps-dev/src/USER-OMP/fix_neigh_history_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nh_asphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nh_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nh_sphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nph_asphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nph_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nph_sphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_npt_asphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_npt_omp.cpp \
../lammps-dev/src/USER-OMP/fix_npt_sphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nve_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nve_sphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nvt_asphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nvt_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nvt_sllod_omp.cpp \
../lammps-dev/src/USER-OMP/fix_nvt_sphere_omp.cpp \
../lammps-dev/src/USER-OMP/fix_omp.cpp \
../lammps-dev/src/USER-OMP/fix_peri_neigh_omp.cpp \
../lammps-dev/src/USER-OMP/fix_qeq_comb_omp.cpp \
../lammps-dev/src/USER-OMP/fix_qeq_reax_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_nh_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_nph_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_npt_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_nve_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_nvt_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_omp.cpp \
../lammps-dev/src/USER-OMP/fix_rigid_small_omp.cpp \
../lammps-dev/src/USER-OMP/improper_class2_omp.cpp \
../lammps-dev/src/USER-OMP/improper_cossq_omp.cpp \
../lammps-dev/src/USER-OMP/improper_cvff_omp.cpp \
../lammps-dev/src/USER-OMP/improper_fourier_omp.cpp \
../lammps-dev/src/USER-OMP/improper_harmonic_omp.cpp \
../lammps-dev/src/USER-OMP/improper_ring_omp.cpp \
../lammps-dev/src/USER-OMP/improper_umbrella_omp.cpp \
../lammps-dev/src/USER-OMP/msm_cg_omp.cpp \
../lammps-dev/src/USER-OMP/msm_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_bin_atomonly_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_bin_ghost_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_bin_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_multi_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_nsq_ghost_omp.cpp \
../lammps-dev/src/USER-OMP/npair_full_nsq_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_bin_atomonly_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_bin_newtoff_ghost_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_bin_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_bin_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_bin_newton_tri_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_multi_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_multi_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_multi_newton_tri_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_ghost_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_nsq_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_respa_bin_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_tri_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_respa_nsq_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_respa_nsq_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_bin_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_bin_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_bin_newton_tri_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_multi_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_multi_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_multi_newton_tri_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_nsq_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_half_size_nsq_newton_omp.cpp \
../lammps-dev/src/USER-OMP/npair_halffull_newtoff_omp.cpp \
../lammps-dev/src/USER-OMP/npair_halffull_newton_omp.cpp \
../lammps-dev/src/USER-OMP/pair_adp_omp.cpp \
../lammps-dev/src/USER-OMP/pair_agni_omp.cpp \
../lammps-dev/src/USER-OMP/pair_airebo_morse_omp.cpp \
../lammps-dev/src/USER-OMP/pair_airebo_omp.cpp \
../lammps-dev/src/USER-OMP/pair_beck_omp.cpp \
../lammps-dev/src/USER-OMP/pair_born_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_born_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_born_coul_wolf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_born_omp.cpp \
../lammps-dev/src/USER-OMP/pair_brownian_omp.cpp \
../lammps-dev/src/USER-OMP/pair_brownian_poly_omp.cpp \
../lammps-dev/src/USER-OMP/pair_buck_coul_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_buck_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_buck_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_buck_long_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_buck_omp.cpp \
../lammps-dev/src/USER-OMP/pair_colloid_omp.cpp \
../lammps-dev/src/USER-OMP/pair_comb_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_cut_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_debye_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_diel_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_dsf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_long_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_coul_wolf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_dpd_omp.cpp \
../lammps-dev/src/USER-OMP/pair_dpd_tstat_omp.cpp \
../lammps-dev/src/USER-OMP/pair_eam_alloy_omp.cpp \
../lammps-dev/src/USER-OMP/pair_eam_cd_omp.cpp \
../lammps-dev/src/USER-OMP/pair_eam_fs_omp.cpp \
../lammps-dev/src/USER-OMP/pair_eam_omp.cpp \
../lammps-dev/src/USER-OMP/pair_edip_omp.cpp \
../lammps-dev/src/USER-OMP/pair_eim_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gauss_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gauss_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gayberne_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gran_hertz_history_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gran_hooke_history_omp.cpp \
../lammps-dev/src/USER-OMP/pair_gran_hooke_omp.cpp \
../lammps-dev/src/USER-OMP/pair_hbond_dreiding_lj_omp.cpp \
../lammps-dev/src/USER-OMP/pair_hbond_dreiding_morse_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj96_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_implicit_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_charmm_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_class2_coul_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_class2_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_class2_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cubic_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_debye_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_dsf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_coul_wolf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_dipole_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_thole_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_expand_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_gromacs_coul_gromacs_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_gromacs_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_long_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_long_tip4p_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_relres_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_sdk_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_sdk_coul_msm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_sdk_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_sf_dipole_sf_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_smooth_linear_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lj_smooth_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lubricate_omp.cpp \
../lammps-dev/src/USER-OMP/pair_lubricate_poly_omp.cpp \
../lammps-dev/src/USER-OMP/pair_meam_spline_omp.cpp \
../lammps-dev/src/USER-OMP/pair_morse_omp.cpp \
../lammps-dev/src/USER-OMP/pair_morse_smooth_linear_omp.cpp \
../lammps-dev/src/USER-OMP/pair_nm_cut_coul_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_nm_cut_coul_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_nm_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_peri_lps_omp.cpp \
../lammps-dev/src/USER-OMP/pair_peri_pmb_omp.cpp \
../lammps-dev/src/USER-OMP/pair_reaxc_omp.cpp \
../lammps-dev/src/USER-OMP/pair_rebo_omp.cpp \
../lammps-dev/src/USER-OMP/pair_resquared_omp.cpp \
../lammps-dev/src/USER-OMP/pair_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_sw_omp.cpp \
../lammps-dev/src/USER-OMP/pair_table_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tersoff_mod_c_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tersoff_mod_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tersoff_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tersoff_table_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tersoff_zbl_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tip4p_cut_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tip4p_long_omp.cpp \
../lammps-dev/src/USER-OMP/pair_tip4p_long_soft_omp.cpp \
../lammps-dev/src/USER-OMP/pair_ufm_omp.cpp \
../lammps-dev/src/USER-OMP/pair_vashishta_omp.cpp \
../lammps-dev/src/USER-OMP/pair_vashishta_table_omp.cpp \
../lammps-dev/src/USER-OMP/pair_yukawa_colloid_omp.cpp \
../lammps-dev/src/USER-OMP/pair_yukawa_omp.cpp \
../lammps-dev/src/USER-OMP/pair_zbl_omp.cpp \
../lammps-dev/src/USER-OMP/pppm_cg_omp.cpp \
../lammps-dev/src/USER-OMP/pppm_disp_omp.cpp \
../lammps-dev/src/USER-OMP/pppm_disp_tip4p_omp.cpp \
../lammps-dev/src/USER-OMP/pppm_omp.cpp \
../lammps-dev/src/USER-OMP/pppm_tip4p_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_bond_orders_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_bonds_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_forces_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_hydrogen_bonds_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_init_md_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_multi_body_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_nonbonded_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_torsion_angles_omp.cpp \
../lammps-dev/src/USER-OMP/reaxc_valence_angles_omp.cpp \
../lammps-dev/src/USER-OMP/respa_omp.cpp \
../lammps-dev/src/USER-OMP/thr_data.cpp \
../lammps-dev/src/USER-OMP/thr_omp.cpp 

OBJS += \
./lammps-dev/src/USER-OMP/angle_charmm_omp.o \
./lammps-dev/src/USER-OMP/angle_class2_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_delta_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_periodic_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_shift_exp_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_shift_omp.o \
./lammps-dev/src/USER-OMP/angle_cosine_squared_omp.o \
./lammps-dev/src/USER-OMP/angle_dipole_omp.o \
./lammps-dev/src/USER-OMP/angle_fourier_omp.o \
./lammps-dev/src/USER-OMP/angle_fourier_simple_omp.o \
./lammps-dev/src/USER-OMP/angle_harmonic_omp.o \
./lammps-dev/src/USER-OMP/angle_quartic_omp.o \
./lammps-dev/src/USER-OMP/angle_sdk_omp.o \
./lammps-dev/src/USER-OMP/angle_table_omp.o \
./lammps-dev/src/USER-OMP/bond_class2_omp.o \
./lammps-dev/src/USER-OMP/bond_fene_expand_omp.o \
./lammps-dev/src/USER-OMP/bond_fene_omp.o \
./lammps-dev/src/USER-OMP/bond_gromos_omp.o \
./lammps-dev/src/USER-OMP/bond_harmonic_omp.o \
./lammps-dev/src/USER-OMP/bond_harmonic_shift_cut_omp.o \
./lammps-dev/src/USER-OMP/bond_harmonic_shift_omp.o \
./lammps-dev/src/USER-OMP/bond_morse_omp.o \
./lammps-dev/src/USER-OMP/bond_nonlinear_omp.o \
./lammps-dev/src/USER-OMP/bond_quartic_omp.o \
./lammps-dev/src/USER-OMP/bond_table_omp.o \
./lammps-dev/src/USER-OMP/dihedral_charmm_omp.o \
./lammps-dev/src/USER-OMP/dihedral_class2_omp.o \
./lammps-dev/src/USER-OMP/dihedral_cosine_shift_exp_omp.o \
./lammps-dev/src/USER-OMP/dihedral_fourier_omp.o \
./lammps-dev/src/USER-OMP/dihedral_harmonic_omp.o \
./lammps-dev/src/USER-OMP/dihedral_helix_omp.o \
./lammps-dev/src/USER-OMP/dihedral_multi_harmonic_omp.o \
./lammps-dev/src/USER-OMP/dihedral_nharmonic_omp.o \
./lammps-dev/src/USER-OMP/dihedral_opls_omp.o \
./lammps-dev/src/USER-OMP/dihedral_quadratic_omp.o \
./lammps-dev/src/USER-OMP/dihedral_table_omp.o \
./lammps-dev/src/USER-OMP/domain_omp.o \
./lammps-dev/src/USER-OMP/ewald_omp.o \
./lammps-dev/src/USER-OMP/fix_gravity_omp.o \
./lammps-dev/src/USER-OMP/fix_neigh_history_omp.o \
./lammps-dev/src/USER-OMP/fix_nh_asphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nh_omp.o \
./lammps-dev/src/USER-OMP/fix_nh_sphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nph_asphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nph_omp.o \
./lammps-dev/src/USER-OMP/fix_nph_sphere_omp.o \
./lammps-dev/src/USER-OMP/fix_npt_asphere_omp.o \
./lammps-dev/src/USER-OMP/fix_npt_omp.o \
./lammps-dev/src/USER-OMP/fix_npt_sphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nve_omp.o \
./lammps-dev/src/USER-OMP/fix_nve_sphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nvt_asphere_omp.o \
./lammps-dev/src/USER-OMP/fix_nvt_omp.o \
./lammps-dev/src/USER-OMP/fix_nvt_sllod_omp.o \
./lammps-dev/src/USER-OMP/fix_nvt_sphere_omp.o \
./lammps-dev/src/USER-OMP/fix_omp.o \
./lammps-dev/src/USER-OMP/fix_peri_neigh_omp.o \
./lammps-dev/src/USER-OMP/fix_qeq_comb_omp.o \
./lammps-dev/src/USER-OMP/fix_qeq_reax_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_nh_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_nph_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_npt_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_nve_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_nvt_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_omp.o \
./lammps-dev/src/USER-OMP/fix_rigid_small_omp.o \
./lammps-dev/src/USER-OMP/improper_class2_omp.o \
./lammps-dev/src/USER-OMP/improper_cossq_omp.o \
./lammps-dev/src/USER-OMP/improper_cvff_omp.o \
./lammps-dev/src/USER-OMP/improper_fourier_omp.o \
./lammps-dev/src/USER-OMP/improper_harmonic_omp.o \
./lammps-dev/src/USER-OMP/improper_ring_omp.o \
./lammps-dev/src/USER-OMP/improper_umbrella_omp.o \
./lammps-dev/src/USER-OMP/msm_cg_omp.o \
./lammps-dev/src/USER-OMP/msm_omp.o \
./lammps-dev/src/USER-OMP/npair_full_bin_atomonly_omp.o \
./lammps-dev/src/USER-OMP/npair_full_bin_ghost_omp.o \
./lammps-dev/src/USER-OMP/npair_full_bin_omp.o \
./lammps-dev/src/USER-OMP/npair_full_multi_omp.o \
./lammps-dev/src/USER-OMP/npair_full_nsq_ghost_omp.o \
./lammps-dev/src/USER-OMP/npair_full_nsq_omp.o \
./lammps-dev/src/USER-OMP/npair_half_bin_atomonly_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_bin_newtoff_ghost_omp.o \
./lammps-dev/src/USER-OMP/npair_half_bin_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_bin_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_bin_newton_tri_omp.o \
./lammps-dev/src/USER-OMP/npair_half_multi_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_multi_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_multi_newton_tri_omp.o \
./lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_ghost_omp.o \
./lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_nsq_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_tri_omp.o \
./lammps-dev/src/USER-OMP/npair_half_respa_nsq_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_respa_nsq_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newton_tri_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newton_tri_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_nsq_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_half_size_nsq_newton_omp.o \
./lammps-dev/src/USER-OMP/npair_halffull_newtoff_omp.o \
./lammps-dev/src/USER-OMP/npair_halffull_newton_omp.o \
./lammps-dev/src/USER-OMP/pair_adp_omp.o \
./lammps-dev/src/USER-OMP/pair_agni_omp.o \
./lammps-dev/src/USER-OMP/pair_airebo_morse_omp.o \
./lammps-dev/src/USER-OMP/pair_airebo_omp.o \
./lammps-dev/src/USER-OMP/pair_beck_omp.o \
./lammps-dev/src/USER-OMP/pair_born_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_born_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_born_coul_wolf_omp.o \
./lammps-dev/src/USER-OMP/pair_born_omp.o \
./lammps-dev/src/USER-OMP/pair_brownian_omp.o \
./lammps-dev/src/USER-OMP/pair_brownian_poly_omp.o \
./lammps-dev/src/USER-OMP/pair_buck_coul_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_buck_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_buck_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_buck_long_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_buck_omp.o \
./lammps-dev/src/USER-OMP/pair_colloid_omp.o \
./lammps-dev/src/USER-OMP/pair_comb_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_cut_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_debye_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_diel_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_dsf_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_long_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_coul_wolf_omp.o \
./lammps-dev/src/USER-OMP/pair_dpd_omp.o \
./lammps-dev/src/USER-OMP/pair_dpd_tstat_omp.o \
./lammps-dev/src/USER-OMP/pair_eam_alloy_omp.o \
./lammps-dev/src/USER-OMP/pair_eam_cd_omp.o \
./lammps-dev/src/USER-OMP/pair_eam_fs_omp.o \
./lammps-dev/src/USER-OMP/pair_eam_omp.o \
./lammps-dev/src/USER-OMP/pair_edip_omp.o \
./lammps-dev/src/USER-OMP/pair_eim_omp.o \
./lammps-dev/src/USER-OMP/pair_gauss_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_gauss_omp.o \
./lammps-dev/src/USER-OMP/pair_gayberne_omp.o \
./lammps-dev/src/USER-OMP/pair_gran_hertz_history_omp.o \
./lammps-dev/src/USER-OMP/pair_gran_hooke_history_omp.o \
./lammps-dev/src/USER-OMP/pair_gran_hooke_omp.o \
./lammps-dev/src/USER-OMP/pair_hbond_dreiding_lj_omp.o \
./lammps-dev/src/USER-OMP/pair_hbond_dreiding_morse_omp.o \
./lammps-dev/src/USER-OMP/pair_lj96_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_implicit_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_class2_coul_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_class2_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_class2_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cubic_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_debye_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_dsf_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_wolf_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_dipole_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_thole_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_expand_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_gromacs_coul_gromacs_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_gromacs_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_long_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_long_tip4p_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_relres_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_sdk_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_sdk_coul_msm_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_sdk_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_sf_dipole_sf_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_smooth_linear_omp.o \
./lammps-dev/src/USER-OMP/pair_lj_smooth_omp.o \
./lammps-dev/src/USER-OMP/pair_lubricate_omp.o \
./lammps-dev/src/USER-OMP/pair_lubricate_poly_omp.o \
./lammps-dev/src/USER-OMP/pair_meam_spline_omp.o \
./lammps-dev/src/USER-OMP/pair_morse_omp.o \
./lammps-dev/src/USER-OMP/pair_morse_smooth_linear_omp.o \
./lammps-dev/src/USER-OMP/pair_nm_cut_coul_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_nm_cut_coul_long_omp.o \
./lammps-dev/src/USER-OMP/pair_nm_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_peri_lps_omp.o \
./lammps-dev/src/USER-OMP/pair_peri_pmb_omp.o \
./lammps-dev/src/USER-OMP/pair_reaxc_omp.o \
./lammps-dev/src/USER-OMP/pair_rebo_omp.o \
./lammps-dev/src/USER-OMP/pair_resquared_omp.o \
./lammps-dev/src/USER-OMP/pair_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_sw_omp.o \
./lammps-dev/src/USER-OMP/pair_table_omp.o \
./lammps-dev/src/USER-OMP/pair_tersoff_mod_c_omp.o \
./lammps-dev/src/USER-OMP/pair_tersoff_mod_omp.o \
./lammps-dev/src/USER-OMP/pair_tersoff_omp.o \
./lammps-dev/src/USER-OMP/pair_tersoff_table_omp.o \
./lammps-dev/src/USER-OMP/pair_tersoff_zbl_omp.o \
./lammps-dev/src/USER-OMP/pair_tip4p_cut_omp.o \
./lammps-dev/src/USER-OMP/pair_tip4p_long_omp.o \
./lammps-dev/src/USER-OMP/pair_tip4p_long_soft_omp.o \
./lammps-dev/src/USER-OMP/pair_ufm_omp.o \
./lammps-dev/src/USER-OMP/pair_vashishta_omp.o \
./lammps-dev/src/USER-OMP/pair_vashishta_table_omp.o \
./lammps-dev/src/USER-OMP/pair_yukawa_colloid_omp.o \
./lammps-dev/src/USER-OMP/pair_yukawa_omp.o \
./lammps-dev/src/USER-OMP/pair_zbl_omp.o \
./lammps-dev/src/USER-OMP/pppm_cg_omp.o \
./lammps-dev/src/USER-OMP/pppm_disp_omp.o \
./lammps-dev/src/USER-OMP/pppm_disp_tip4p_omp.o \
./lammps-dev/src/USER-OMP/pppm_omp.o \
./lammps-dev/src/USER-OMP/pppm_tip4p_omp.o \
./lammps-dev/src/USER-OMP/reaxc_bond_orders_omp.o \
./lammps-dev/src/USER-OMP/reaxc_bonds_omp.o \
./lammps-dev/src/USER-OMP/reaxc_forces_omp.o \
./lammps-dev/src/USER-OMP/reaxc_hydrogen_bonds_omp.o \
./lammps-dev/src/USER-OMP/reaxc_init_md_omp.o \
./lammps-dev/src/USER-OMP/reaxc_multi_body_omp.o \
./lammps-dev/src/USER-OMP/reaxc_nonbonded_omp.o \
./lammps-dev/src/USER-OMP/reaxc_torsion_angles_omp.o \
./lammps-dev/src/USER-OMP/reaxc_valence_angles_omp.o \
./lammps-dev/src/USER-OMP/respa_omp.o \
./lammps-dev/src/USER-OMP/thr_data.o \
./lammps-dev/src/USER-OMP/thr_omp.o 

CPP_DEPS += \
./lammps-dev/src/USER-OMP/angle_charmm_omp.d \
./lammps-dev/src/USER-OMP/angle_class2_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_delta_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_periodic_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_shift_exp_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_shift_omp.d \
./lammps-dev/src/USER-OMP/angle_cosine_squared_omp.d \
./lammps-dev/src/USER-OMP/angle_dipole_omp.d \
./lammps-dev/src/USER-OMP/angle_fourier_omp.d \
./lammps-dev/src/USER-OMP/angle_fourier_simple_omp.d \
./lammps-dev/src/USER-OMP/angle_harmonic_omp.d \
./lammps-dev/src/USER-OMP/angle_quartic_omp.d \
./lammps-dev/src/USER-OMP/angle_sdk_omp.d \
./lammps-dev/src/USER-OMP/angle_table_omp.d \
./lammps-dev/src/USER-OMP/bond_class2_omp.d \
./lammps-dev/src/USER-OMP/bond_fene_expand_omp.d \
./lammps-dev/src/USER-OMP/bond_fene_omp.d \
./lammps-dev/src/USER-OMP/bond_gromos_omp.d \
./lammps-dev/src/USER-OMP/bond_harmonic_omp.d \
./lammps-dev/src/USER-OMP/bond_harmonic_shift_cut_omp.d \
./lammps-dev/src/USER-OMP/bond_harmonic_shift_omp.d \
./lammps-dev/src/USER-OMP/bond_morse_omp.d \
./lammps-dev/src/USER-OMP/bond_nonlinear_omp.d \
./lammps-dev/src/USER-OMP/bond_quartic_omp.d \
./lammps-dev/src/USER-OMP/bond_table_omp.d \
./lammps-dev/src/USER-OMP/dihedral_charmm_omp.d \
./lammps-dev/src/USER-OMP/dihedral_class2_omp.d \
./lammps-dev/src/USER-OMP/dihedral_cosine_shift_exp_omp.d \
./lammps-dev/src/USER-OMP/dihedral_fourier_omp.d \
./lammps-dev/src/USER-OMP/dihedral_harmonic_omp.d \
./lammps-dev/src/USER-OMP/dihedral_helix_omp.d \
./lammps-dev/src/USER-OMP/dihedral_multi_harmonic_omp.d \
./lammps-dev/src/USER-OMP/dihedral_nharmonic_omp.d \
./lammps-dev/src/USER-OMP/dihedral_opls_omp.d \
./lammps-dev/src/USER-OMP/dihedral_quadratic_omp.d \
./lammps-dev/src/USER-OMP/dihedral_table_omp.d \
./lammps-dev/src/USER-OMP/domain_omp.d \
./lammps-dev/src/USER-OMP/ewald_omp.d \
./lammps-dev/src/USER-OMP/fix_gravity_omp.d \
./lammps-dev/src/USER-OMP/fix_neigh_history_omp.d \
./lammps-dev/src/USER-OMP/fix_nh_asphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nh_omp.d \
./lammps-dev/src/USER-OMP/fix_nh_sphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nph_asphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nph_omp.d \
./lammps-dev/src/USER-OMP/fix_nph_sphere_omp.d \
./lammps-dev/src/USER-OMP/fix_npt_asphere_omp.d \
./lammps-dev/src/USER-OMP/fix_npt_omp.d \
./lammps-dev/src/USER-OMP/fix_npt_sphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nve_omp.d \
./lammps-dev/src/USER-OMP/fix_nve_sphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nvt_asphere_omp.d \
./lammps-dev/src/USER-OMP/fix_nvt_omp.d \
./lammps-dev/src/USER-OMP/fix_nvt_sllod_omp.d \
./lammps-dev/src/USER-OMP/fix_nvt_sphere_omp.d \
./lammps-dev/src/USER-OMP/fix_omp.d \
./lammps-dev/src/USER-OMP/fix_peri_neigh_omp.d \
./lammps-dev/src/USER-OMP/fix_qeq_comb_omp.d \
./lammps-dev/src/USER-OMP/fix_qeq_reax_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_nh_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_nph_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_npt_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_nve_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_nvt_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_omp.d \
./lammps-dev/src/USER-OMP/fix_rigid_small_omp.d \
./lammps-dev/src/USER-OMP/improper_class2_omp.d \
./lammps-dev/src/USER-OMP/improper_cossq_omp.d \
./lammps-dev/src/USER-OMP/improper_cvff_omp.d \
./lammps-dev/src/USER-OMP/improper_fourier_omp.d \
./lammps-dev/src/USER-OMP/improper_harmonic_omp.d \
./lammps-dev/src/USER-OMP/improper_ring_omp.d \
./lammps-dev/src/USER-OMP/improper_umbrella_omp.d \
./lammps-dev/src/USER-OMP/msm_cg_omp.d \
./lammps-dev/src/USER-OMP/msm_omp.d \
./lammps-dev/src/USER-OMP/npair_full_bin_atomonly_omp.d \
./lammps-dev/src/USER-OMP/npair_full_bin_ghost_omp.d \
./lammps-dev/src/USER-OMP/npair_full_bin_omp.d \
./lammps-dev/src/USER-OMP/npair_full_multi_omp.d \
./lammps-dev/src/USER-OMP/npair_full_nsq_ghost_omp.d \
./lammps-dev/src/USER-OMP/npair_full_nsq_omp.d \
./lammps-dev/src/USER-OMP/npair_half_bin_atomonly_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_bin_newtoff_ghost_omp.d \
./lammps-dev/src/USER-OMP/npair_half_bin_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_bin_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_bin_newton_tri_omp.d \
./lammps-dev/src/USER-OMP/npair_half_multi_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_multi_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_multi_newton_tri_omp.d \
./lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_ghost_omp.d \
./lammps-dev/src/USER-OMP/npair_half_nsq_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_nsq_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_respa_bin_newton_tri_omp.d \
./lammps-dev/src/USER-OMP/npair_half_respa_nsq_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_respa_nsq_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_bin_newton_tri_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_multi_newton_tri_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_nsq_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_half_size_nsq_newton_omp.d \
./lammps-dev/src/USER-OMP/npair_halffull_newtoff_omp.d \
./lammps-dev/src/USER-OMP/npair_halffull_newton_omp.d \
./lammps-dev/src/USER-OMP/pair_adp_omp.d \
./lammps-dev/src/USER-OMP/pair_agni_omp.d \
./lammps-dev/src/USER-OMP/pair_airebo_morse_omp.d \
./lammps-dev/src/USER-OMP/pair_airebo_omp.d \
./lammps-dev/src/USER-OMP/pair_beck_omp.d \
./lammps-dev/src/USER-OMP/pair_born_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_born_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_born_coul_wolf_omp.d \
./lammps-dev/src/USER-OMP/pair_born_omp.d \
./lammps-dev/src/USER-OMP/pair_brownian_omp.d \
./lammps-dev/src/USER-OMP/pair_brownian_poly_omp.d \
./lammps-dev/src/USER-OMP/pair_buck_coul_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_buck_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_buck_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_buck_long_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_buck_omp.d \
./lammps-dev/src/USER-OMP/pair_colloid_omp.d \
./lammps-dev/src/USER-OMP/pair_comb_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_cut_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_debye_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_diel_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_dsf_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_long_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_coul_wolf_omp.d \
./lammps-dev/src/USER-OMP/pair_dpd_omp.d \
./lammps-dev/src/USER-OMP/pair_dpd_tstat_omp.d \
./lammps-dev/src/USER-OMP/pair_eam_alloy_omp.d \
./lammps-dev/src/USER-OMP/pair_eam_cd_omp.d \
./lammps-dev/src/USER-OMP/pair_eam_fs_omp.d \
./lammps-dev/src/USER-OMP/pair_eam_omp.d \
./lammps-dev/src/USER-OMP/pair_edip_omp.d \
./lammps-dev/src/USER-OMP/pair_eim_omp.d \
./lammps-dev/src/USER-OMP/pair_gauss_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_gauss_omp.d \
./lammps-dev/src/USER-OMP/pair_gayberne_omp.d \
./lammps-dev/src/USER-OMP/pair_gran_hertz_history_omp.d \
./lammps-dev/src/USER-OMP/pair_gran_hooke_history_omp.d \
./lammps-dev/src/USER-OMP/pair_gran_hooke_omp.d \
./lammps-dev/src/USER-OMP/pair_hbond_dreiding_lj_omp.d \
./lammps-dev/src/USER-OMP/pair_hbond_dreiding_morse_omp.d \
./lammps-dev/src/USER-OMP/pair_lj96_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_implicit_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_charmm_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_long_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_charmm_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_class2_coul_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_class2_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_class2_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cubic_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_cut_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_debye_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_dsf_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_long_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_coul_wolf_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_dipole_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_thole_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_cut_tip4p_long_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_expand_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_gromacs_coul_gromacs_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_gromacs_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_long_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_long_tip4p_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_relres_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_sdk_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_sdk_coul_msm_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_sdk_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_sf_dipole_sf_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_smooth_linear_omp.d \
./lammps-dev/src/USER-OMP/pair_lj_smooth_omp.d \
./lammps-dev/src/USER-OMP/pair_lubricate_omp.d \
./lammps-dev/src/USER-OMP/pair_lubricate_poly_omp.d \
./lammps-dev/src/USER-OMP/pair_meam_spline_omp.d \
./lammps-dev/src/USER-OMP/pair_morse_omp.d \
./lammps-dev/src/USER-OMP/pair_morse_smooth_linear_omp.d \
./lammps-dev/src/USER-OMP/pair_nm_cut_coul_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_nm_cut_coul_long_omp.d \
./lammps-dev/src/USER-OMP/pair_nm_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_peri_lps_omp.d \
./lammps-dev/src/USER-OMP/pair_peri_pmb_omp.d \
./lammps-dev/src/USER-OMP/pair_reaxc_omp.d \
./lammps-dev/src/USER-OMP/pair_rebo_omp.d \
./lammps-dev/src/USER-OMP/pair_resquared_omp.d \
./lammps-dev/src/USER-OMP/pair_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_sw_omp.d \
./lammps-dev/src/USER-OMP/pair_table_omp.d \
./lammps-dev/src/USER-OMP/pair_tersoff_mod_c_omp.d \
./lammps-dev/src/USER-OMP/pair_tersoff_mod_omp.d \
./lammps-dev/src/USER-OMP/pair_tersoff_omp.d \
./lammps-dev/src/USER-OMP/pair_tersoff_table_omp.d \
./lammps-dev/src/USER-OMP/pair_tersoff_zbl_omp.d \
./lammps-dev/src/USER-OMP/pair_tip4p_cut_omp.d \
./lammps-dev/src/USER-OMP/pair_tip4p_long_omp.d \
./lammps-dev/src/USER-OMP/pair_tip4p_long_soft_omp.d \
./lammps-dev/src/USER-OMP/pair_ufm_omp.d \
./lammps-dev/src/USER-OMP/pair_vashishta_omp.d \
./lammps-dev/src/USER-OMP/pair_vashishta_table_omp.d \
./lammps-dev/src/USER-OMP/pair_yukawa_colloid_omp.d \
./lammps-dev/src/USER-OMP/pair_yukawa_omp.d \
./lammps-dev/src/USER-OMP/pair_zbl_omp.d \
./lammps-dev/src/USER-OMP/pppm_cg_omp.d \
./lammps-dev/src/USER-OMP/pppm_disp_omp.d \
./lammps-dev/src/USER-OMP/pppm_disp_tip4p_omp.d \
./lammps-dev/src/USER-OMP/pppm_omp.d \
./lammps-dev/src/USER-OMP/pppm_tip4p_omp.d \
./lammps-dev/src/USER-OMP/reaxc_bond_orders_omp.d \
./lammps-dev/src/USER-OMP/reaxc_bonds_omp.d \
./lammps-dev/src/USER-OMP/reaxc_forces_omp.d \
./lammps-dev/src/USER-OMP/reaxc_hydrogen_bonds_omp.d \
./lammps-dev/src/USER-OMP/reaxc_init_md_omp.d \
./lammps-dev/src/USER-OMP/reaxc_multi_body_omp.d \
./lammps-dev/src/USER-OMP/reaxc_nonbonded_omp.d \
./lammps-dev/src/USER-OMP/reaxc_torsion_angles_omp.d \
./lammps-dev/src/USER-OMP/reaxc_valence_angles_omp.d \
./lammps-dev/src/USER-OMP/respa_omp.d \
./lammps-dev/src/USER-OMP/thr_data.d \
./lammps-dev/src/USER-OMP/thr_omp.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/src/USER-OMP/%.o: ../lammps-dev/src/USER-OMP/%.cpp lammps-dev/src/USER-OMP/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


