################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/lib/atc/ATC_Coupling.cpp \
../lammps-dev/lib/atc/ATC_CouplingEnergy.cpp \
../lammps-dev/lib/atc/ATC_CouplingMass.cpp \
../lammps-dev/lib/atc/ATC_CouplingMomentum.cpp \
../lammps-dev/lib/atc/ATC_CouplingMomentumEnergy.cpp \
../lammps-dev/lib/atc/ATC_Method.cpp \
../lammps-dev/lib/atc/ATC_Transfer.cpp \
../lammps-dev/lib/atc/ATC_TransferKernel.cpp \
../lammps-dev/lib/atc/ATC_TransferPartitionOfUnity.cpp \
../lammps-dev/lib/atc/AtomToMoleculeTransfer.cpp \
../lammps-dev/lib/atc/AtomicRegulator.cpp \
../lammps-dev/lib/atc/BodyForce.cpp \
../lammps-dev/lib/atc/CBLattice.cpp \
../lammps-dev/lib/atc/CauchyBorn.cpp \
../lammps-dev/lib/atc/CbPotential.cpp \
../lammps-dev/lib/atc/ChargeRegulator.cpp \
../lammps-dev/lib/atc/ConcentrationRegulator.cpp \
../lammps-dev/lib/atc/ElasticTimeIntegrator.cpp \
../lammps-dev/lib/atc/ElectronChargeDensity.cpp \
../lammps-dev/lib/atc/ElectronDragPower.cpp \
../lammps-dev/lib/atc/ElectronFlux.cpp \
../lammps-dev/lib/atc/ElectronHeatCapacity.cpp \
../lammps-dev/lib/atc/ElectronHeatFlux.cpp \
../lammps-dev/lib/atc/ElectronPhononExchange.cpp \
../lammps-dev/lib/atc/ExtrinsicModel.cpp \
../lammps-dev/lib/atc/ExtrinsicModelDriftDiffusion.cpp \
../lammps-dev/lib/atc/ExtrinsicModelElectrostatic.cpp \
../lammps-dev/lib/atc/ExtrinsicModelTwoTemperature.cpp \
../lammps-dev/lib/atc/FE_Element.cpp \
../lammps-dev/lib/atc/FE_Engine.cpp \
../lammps-dev/lib/atc/FE_Interpolate.cpp \
../lammps-dev/lib/atc/FE_Mesh.cpp \
../lammps-dev/lib/atc/FieldEulerIntegrator.cpp \
../lammps-dev/lib/atc/FieldManager.cpp \
../lammps-dev/lib/atc/Function.cpp \
../lammps-dev/lib/atc/FundamentalAtomicQuantity.cpp \
../lammps-dev/lib/atc/GhostManager.cpp \
../lammps-dev/lib/atc/ImplicitSolveOperator.cpp \
../lammps-dev/lib/atc/InterscaleOperators.cpp \
../lammps-dev/lib/atc/KD_Tree.cpp \
../lammps-dev/lib/atc/KernelFunction.cpp \
../lammps-dev/lib/atc/KinetoThermostat.cpp \
../lammps-dev/lib/atc/Kinetostat.cpp \
../lammps-dev/lib/atc/LammpsInterface.cpp \
../lammps-dev/lib/atc/LinearSolver.cpp \
../lammps-dev/lib/atc/MPI_Wrappers.cpp \
../lammps-dev/lib/atc/Material.cpp \
../lammps-dev/lib/atc/Matrix.cpp \
../lammps-dev/lib/atc/MeshReader.cpp \
../lammps-dev/lib/atc/MoleculeSet.cpp \
../lammps-dev/lib/atc/NonLinearSolver.cpp \
../lammps-dev/lib/atc/OutputManager.cpp \
../lammps-dev/lib/atc/PaqAtcUtility.cpp \
../lammps-dev/lib/atc/ParDiagonalMatrix.cpp \
../lammps-dev/lib/atc/ParSparseMatrix.cpp \
../lammps-dev/lib/atc/PerAtomQuantityLibrary.cpp \
../lammps-dev/lib/atc/PerPairQuantity.cpp \
../lammps-dev/lib/atc/PhysicsModel.cpp \
../lammps-dev/lib/atc/PoissonSolver.cpp \
../lammps-dev/lib/atc/PolynomialSolver.cpp \
../lammps-dev/lib/atc/PrescribedDataManager.cpp \
../lammps-dev/lib/atc/Quadrature.cpp \
../lammps-dev/lib/atc/SchrodingerSolver.cpp \
../lammps-dev/lib/atc/SpeciesTimeIntegrator.cpp \
../lammps-dev/lib/atc/Stress.cpp \
../lammps-dev/lib/atc/ThermalTimeIntegrator.cpp \
../lammps-dev/lib/atc/Thermostat.cpp \
../lammps-dev/lib/atc/TimeFilter.cpp \
../lammps-dev/lib/atc/TimeIntegrator.cpp \
../lammps-dev/lib/atc/TransferLibrary.cpp \
../lammps-dev/lib/atc/TransferOperator.cpp \
../lammps-dev/lib/atc/Vector.cpp \
../lammps-dev/lib/atc/ViscousStress.cpp \
../lammps-dev/lib/atc/WeakEquationChargeDiffusion.cpp \
../lammps-dev/lib/atc/WeakEquationDiffusion.cpp \
../lammps-dev/lib/atc/WeakEquationElectronContinuity.cpp \
../lammps-dev/lib/atc/WeakEquationElectronMomentum.cpp \
../lammps-dev/lib/atc/WeakEquationElectronTemperature.cpp \
../lammps-dev/lib/atc/WeakEquationMassDiffusion.cpp \
../lammps-dev/lib/atc/WeakEquationMomentum.cpp \
../lammps-dev/lib/atc/WeakEquationPhononTemperature.cpp \
../lammps-dev/lib/atc/WeakEquationPoisson.cpp \
../lammps-dev/lib/atc/WeakEquationSchrodinger.cpp 

OBJS += \
./lammps-dev/lib/atc/ATC_Coupling.o \
./lammps-dev/lib/atc/ATC_CouplingEnergy.o \
./lammps-dev/lib/atc/ATC_CouplingMass.o \
./lammps-dev/lib/atc/ATC_CouplingMomentum.o \
./lammps-dev/lib/atc/ATC_CouplingMomentumEnergy.o \
./lammps-dev/lib/atc/ATC_Method.o \
./lammps-dev/lib/atc/ATC_Transfer.o \
./lammps-dev/lib/atc/ATC_TransferKernel.o \
./lammps-dev/lib/atc/ATC_TransferPartitionOfUnity.o \
./lammps-dev/lib/atc/AtomToMoleculeTransfer.o \
./lammps-dev/lib/atc/AtomicRegulator.o \
./lammps-dev/lib/atc/BodyForce.o \
./lammps-dev/lib/atc/CBLattice.o \
./lammps-dev/lib/atc/CauchyBorn.o \
./lammps-dev/lib/atc/CbPotential.o \
./lammps-dev/lib/atc/ChargeRegulator.o \
./lammps-dev/lib/atc/ConcentrationRegulator.o \
./lammps-dev/lib/atc/ElasticTimeIntegrator.o \
./lammps-dev/lib/atc/ElectronChargeDensity.o \
./lammps-dev/lib/atc/ElectronDragPower.o \
./lammps-dev/lib/atc/ElectronFlux.o \
./lammps-dev/lib/atc/ElectronHeatCapacity.o \
./lammps-dev/lib/atc/ElectronHeatFlux.o \
./lammps-dev/lib/atc/ElectronPhononExchange.o \
./lammps-dev/lib/atc/ExtrinsicModel.o \
./lammps-dev/lib/atc/ExtrinsicModelDriftDiffusion.o \
./lammps-dev/lib/atc/ExtrinsicModelElectrostatic.o \
./lammps-dev/lib/atc/ExtrinsicModelTwoTemperature.o \
./lammps-dev/lib/atc/FE_Element.o \
./lammps-dev/lib/atc/FE_Engine.o \
./lammps-dev/lib/atc/FE_Interpolate.o \
./lammps-dev/lib/atc/FE_Mesh.o \
./lammps-dev/lib/atc/FieldEulerIntegrator.o \
./lammps-dev/lib/atc/FieldManager.o \
./lammps-dev/lib/atc/Function.o \
./lammps-dev/lib/atc/FundamentalAtomicQuantity.o \
./lammps-dev/lib/atc/GhostManager.o \
./lammps-dev/lib/atc/ImplicitSolveOperator.o \
./lammps-dev/lib/atc/InterscaleOperators.o \
./lammps-dev/lib/atc/KD_Tree.o \
./lammps-dev/lib/atc/KernelFunction.o \
./lammps-dev/lib/atc/KinetoThermostat.o \
./lammps-dev/lib/atc/Kinetostat.o \
./lammps-dev/lib/atc/LammpsInterface.o \
./lammps-dev/lib/atc/LinearSolver.o \
./lammps-dev/lib/atc/MPI_Wrappers.o \
./lammps-dev/lib/atc/Material.o \
./lammps-dev/lib/atc/Matrix.o \
./lammps-dev/lib/atc/MeshReader.o \
./lammps-dev/lib/atc/MoleculeSet.o \
./lammps-dev/lib/atc/NonLinearSolver.o \
./lammps-dev/lib/atc/OutputManager.o \
./lammps-dev/lib/atc/PaqAtcUtility.o \
./lammps-dev/lib/atc/ParDiagonalMatrix.o \
./lammps-dev/lib/atc/ParSparseMatrix.o \
./lammps-dev/lib/atc/PerAtomQuantityLibrary.o \
./lammps-dev/lib/atc/PerPairQuantity.o \
./lammps-dev/lib/atc/PhysicsModel.o \
./lammps-dev/lib/atc/PoissonSolver.o \
./lammps-dev/lib/atc/PolynomialSolver.o \
./lammps-dev/lib/atc/PrescribedDataManager.o \
./lammps-dev/lib/atc/Quadrature.o \
./lammps-dev/lib/atc/SchrodingerSolver.o \
./lammps-dev/lib/atc/SpeciesTimeIntegrator.o \
./lammps-dev/lib/atc/Stress.o \
./lammps-dev/lib/atc/ThermalTimeIntegrator.o \
./lammps-dev/lib/atc/Thermostat.o \
./lammps-dev/lib/atc/TimeFilter.o \
./lammps-dev/lib/atc/TimeIntegrator.o \
./lammps-dev/lib/atc/TransferLibrary.o \
./lammps-dev/lib/atc/TransferOperator.o \
./lammps-dev/lib/atc/Vector.o \
./lammps-dev/lib/atc/ViscousStress.o \
./lammps-dev/lib/atc/WeakEquationChargeDiffusion.o \
./lammps-dev/lib/atc/WeakEquationDiffusion.o \
./lammps-dev/lib/atc/WeakEquationElectronContinuity.o \
./lammps-dev/lib/atc/WeakEquationElectronMomentum.o \
./lammps-dev/lib/atc/WeakEquationElectronTemperature.o \
./lammps-dev/lib/atc/WeakEquationMassDiffusion.o \
./lammps-dev/lib/atc/WeakEquationMomentum.o \
./lammps-dev/lib/atc/WeakEquationPhononTemperature.o \
./lammps-dev/lib/atc/WeakEquationPoisson.o \
./lammps-dev/lib/atc/WeakEquationSchrodinger.o 

CPP_DEPS += \
./lammps-dev/lib/atc/ATC_Coupling.d \
./lammps-dev/lib/atc/ATC_CouplingEnergy.d \
./lammps-dev/lib/atc/ATC_CouplingMass.d \
./lammps-dev/lib/atc/ATC_CouplingMomentum.d \
./lammps-dev/lib/atc/ATC_CouplingMomentumEnergy.d \
./lammps-dev/lib/atc/ATC_Method.d \
./lammps-dev/lib/atc/ATC_Transfer.d \
./lammps-dev/lib/atc/ATC_TransferKernel.d \
./lammps-dev/lib/atc/ATC_TransferPartitionOfUnity.d \
./lammps-dev/lib/atc/AtomToMoleculeTransfer.d \
./lammps-dev/lib/atc/AtomicRegulator.d \
./lammps-dev/lib/atc/BodyForce.d \
./lammps-dev/lib/atc/CBLattice.d \
./lammps-dev/lib/atc/CauchyBorn.d \
./lammps-dev/lib/atc/CbPotential.d \
./lammps-dev/lib/atc/ChargeRegulator.d \
./lammps-dev/lib/atc/ConcentrationRegulator.d \
./lammps-dev/lib/atc/ElasticTimeIntegrator.d \
./lammps-dev/lib/atc/ElectronChargeDensity.d \
./lammps-dev/lib/atc/ElectronDragPower.d \
./lammps-dev/lib/atc/ElectronFlux.d \
./lammps-dev/lib/atc/ElectronHeatCapacity.d \
./lammps-dev/lib/atc/ElectronHeatFlux.d \
./lammps-dev/lib/atc/ElectronPhononExchange.d \
./lammps-dev/lib/atc/ExtrinsicModel.d \
./lammps-dev/lib/atc/ExtrinsicModelDriftDiffusion.d \
./lammps-dev/lib/atc/ExtrinsicModelElectrostatic.d \
./lammps-dev/lib/atc/ExtrinsicModelTwoTemperature.d \
./lammps-dev/lib/atc/FE_Element.d \
./lammps-dev/lib/atc/FE_Engine.d \
./lammps-dev/lib/atc/FE_Interpolate.d \
./lammps-dev/lib/atc/FE_Mesh.d \
./lammps-dev/lib/atc/FieldEulerIntegrator.d \
./lammps-dev/lib/atc/FieldManager.d \
./lammps-dev/lib/atc/Function.d \
./lammps-dev/lib/atc/FundamentalAtomicQuantity.d \
./lammps-dev/lib/atc/GhostManager.d \
./lammps-dev/lib/atc/ImplicitSolveOperator.d \
./lammps-dev/lib/atc/InterscaleOperators.d \
./lammps-dev/lib/atc/KD_Tree.d \
./lammps-dev/lib/atc/KernelFunction.d \
./lammps-dev/lib/atc/KinetoThermostat.d \
./lammps-dev/lib/atc/Kinetostat.d \
./lammps-dev/lib/atc/LammpsInterface.d \
./lammps-dev/lib/atc/LinearSolver.d \
./lammps-dev/lib/atc/MPI_Wrappers.d \
./lammps-dev/lib/atc/Material.d \
./lammps-dev/lib/atc/Matrix.d \
./lammps-dev/lib/atc/MeshReader.d \
./lammps-dev/lib/atc/MoleculeSet.d \
./lammps-dev/lib/atc/NonLinearSolver.d \
./lammps-dev/lib/atc/OutputManager.d \
./lammps-dev/lib/atc/PaqAtcUtility.d \
./lammps-dev/lib/atc/ParDiagonalMatrix.d \
./lammps-dev/lib/atc/ParSparseMatrix.d \
./lammps-dev/lib/atc/PerAtomQuantityLibrary.d \
./lammps-dev/lib/atc/PerPairQuantity.d \
./lammps-dev/lib/atc/PhysicsModel.d \
./lammps-dev/lib/atc/PoissonSolver.d \
./lammps-dev/lib/atc/PolynomialSolver.d \
./lammps-dev/lib/atc/PrescribedDataManager.d \
./lammps-dev/lib/atc/Quadrature.d \
./lammps-dev/lib/atc/SchrodingerSolver.d \
./lammps-dev/lib/atc/SpeciesTimeIntegrator.d \
./lammps-dev/lib/atc/Stress.d \
./lammps-dev/lib/atc/ThermalTimeIntegrator.d \
./lammps-dev/lib/atc/Thermostat.d \
./lammps-dev/lib/atc/TimeFilter.d \
./lammps-dev/lib/atc/TimeIntegrator.d \
./lammps-dev/lib/atc/TransferLibrary.d \
./lammps-dev/lib/atc/TransferOperator.d \
./lammps-dev/lib/atc/Vector.d \
./lammps-dev/lib/atc/ViscousStress.d \
./lammps-dev/lib/atc/WeakEquationChargeDiffusion.d \
./lammps-dev/lib/atc/WeakEquationDiffusion.d \
./lammps-dev/lib/atc/WeakEquationElectronContinuity.d \
./lammps-dev/lib/atc/WeakEquationElectronMomentum.d \
./lammps-dev/lib/atc/WeakEquationElectronTemperature.d \
./lammps-dev/lib/atc/WeakEquationMassDiffusion.d \
./lammps-dev/lib/atc/WeakEquationMomentum.d \
./lammps-dev/lib/atc/WeakEquationPhononTemperature.d \
./lammps-dev/lib/atc/WeakEquationPoisson.d \
./lammps-dev/lib/atc/WeakEquationSchrodinger.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/lib/atc/%.o: ../lammps-dev/lib/atc/%.cpp lammps-dev/lib/atc/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


