################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/src/angle.cpp \
../lammps-dev/src/angle_charmm.cpp \
../lammps-dev/src/angle_cosine.cpp \
../lammps-dev/src/angle_cosine_delta.cpp \
../lammps-dev/src/angle_cosine_periodic.cpp \
../lammps-dev/src/angle_cosine_squared.cpp \
../lammps-dev/src/angle_deprecated.cpp \
../lammps-dev/src/angle_harmonic.cpp \
../lammps-dev/src/angle_hybrid.cpp \
../lammps-dev/src/angle_table.cpp \
../lammps-dev/src/angle_zero.cpp \
../lammps-dev/src/arg_info.cpp \
../lammps-dev/src/atom.cpp \
../lammps-dev/src/atom_map.cpp \
../lammps-dev/src/atom_vec.cpp \
../lammps-dev/src/atom_vec_angle.cpp \
../lammps-dev/src/atom_vec_atomic.cpp \
../lammps-dev/src/atom_vec_body.cpp \
../lammps-dev/src/atom_vec_bond.cpp \
../lammps-dev/src/atom_vec_charge.cpp \
../lammps-dev/src/atom_vec_ellipsoid.cpp \
../lammps-dev/src/atom_vec_full.cpp \
../lammps-dev/src/atom_vec_hybrid.cpp \
../lammps-dev/src/atom_vec_line.cpp \
../lammps-dev/src/atom_vec_molecular.cpp \
../lammps-dev/src/atom_vec_sphere.cpp \
../lammps-dev/src/atom_vec_template.cpp \
../lammps-dev/src/atom_vec_tri.cpp \
../lammps-dev/src/balance.cpp \
../lammps-dev/src/body.cpp \
../lammps-dev/src/bond.cpp \
../lammps-dev/src/bond_deprecated.cpp \
../lammps-dev/src/bond_fene.cpp \
../lammps-dev/src/bond_fene_expand.cpp \
../lammps-dev/src/bond_gromos.cpp \
../lammps-dev/src/bond_harmonic.cpp \
../lammps-dev/src/bond_hybrid.cpp \
../lammps-dev/src/bond_morse.cpp \
../lammps-dev/src/bond_nonlinear.cpp \
../lammps-dev/src/bond_quartic.cpp \
../lammps-dev/src/bond_table.cpp \
../lammps-dev/src/bond_zero.cpp \
../lammps-dev/src/change_box.cpp \
../lammps-dev/src/citeme.cpp \
../lammps-dev/src/comm.cpp \
../lammps-dev/src/comm_brick.cpp \
../lammps-dev/src/comm_tiled.cpp \
../lammps-dev/src/compute.cpp \
../lammps-dev/src/compute_adf.cpp \
../lammps-dev/src/compute_aggregate_atom.cpp \
../lammps-dev/src/compute_angle.cpp \
../lammps-dev/src/compute_angle_local.cpp \
../lammps-dev/src/compute_angmom_chunk.cpp \
../lammps-dev/src/compute_bond.cpp \
../lammps-dev/src/compute_bond_local.cpp \
../lammps-dev/src/compute_centro_atom.cpp \
../lammps-dev/src/compute_centroid_stress_atom.cpp \
../lammps-dev/src/compute_chunk_atom.cpp \
../lammps-dev/src/compute_chunk_spread_atom.cpp \
../lammps-dev/src/compute_cluster_atom.cpp \
../lammps-dev/src/compute_cna_atom.cpp \
../lammps-dev/src/compute_com.cpp \
../lammps-dev/src/compute_com_chunk.cpp \
../lammps-dev/src/compute_contact_atom.cpp \
../lammps-dev/src/compute_coord_atom.cpp \
../lammps-dev/src/compute_deprecated.cpp \
../lammps-dev/src/compute_dihedral.cpp \
../lammps-dev/src/compute_dihedral_local.cpp \
../lammps-dev/src/compute_dipole_chunk.cpp \
../lammps-dev/src/compute_displace_atom.cpp \
../lammps-dev/src/compute_erotate_sphere.cpp \
../lammps-dev/src/compute_erotate_sphere_atom.cpp \
../lammps-dev/src/compute_fragment_atom.cpp \
../lammps-dev/src/compute_global_atom.cpp \
../lammps-dev/src/compute_group_group.cpp \
../lammps-dev/src/compute_gyration.cpp \
../lammps-dev/src/compute_gyration_chunk.cpp \
../lammps-dev/src/compute_heat_flux.cpp \
../lammps-dev/src/compute_hexorder_atom.cpp \
../lammps-dev/src/compute_improper.cpp \
../lammps-dev/src/compute_improper_local.cpp \
../lammps-dev/src/compute_inertia_chunk.cpp \
../lammps-dev/src/compute_ke.cpp \
../lammps-dev/src/compute_ke_atom.cpp \
../lammps-dev/src/compute_msd.cpp \
../lammps-dev/src/compute_msd_chunk.cpp \
../lammps-dev/src/compute_omega_chunk.cpp \
../lammps-dev/src/compute_orientorder_atom.cpp \
../lammps-dev/src/compute_pair.cpp \
../lammps-dev/src/compute_pair_local.cpp \
../lammps-dev/src/compute_pe.cpp \
../lammps-dev/src/compute_pe_atom.cpp \
../lammps-dev/src/compute_pressure.cpp \
../lammps-dev/src/compute_property_atom.cpp \
../lammps-dev/src/compute_property_chunk.cpp \
../lammps-dev/src/compute_property_local.cpp \
../lammps-dev/src/compute_rdf.cpp \
../lammps-dev/src/compute_reduce.cpp \
../lammps-dev/src/compute_reduce_chunk.cpp \
../lammps-dev/src/compute_reduce_region.cpp \
../lammps-dev/src/compute_slice.cpp \
../lammps-dev/src/compute_stress_atom.cpp \
../lammps-dev/src/compute_temp.cpp \
../lammps-dev/src/compute_temp_chunk.cpp \
../lammps-dev/src/compute_temp_com.cpp \
../lammps-dev/src/compute_temp_deform.cpp \
../lammps-dev/src/compute_temp_partial.cpp \
../lammps-dev/src/compute_temp_profile.cpp \
../lammps-dev/src/compute_temp_ramp.cpp \
../lammps-dev/src/compute_temp_region.cpp \
../lammps-dev/src/compute_temp_sphere.cpp \
../lammps-dev/src/compute_torque_chunk.cpp \
../lammps-dev/src/compute_vacf.cpp \
../lammps-dev/src/compute_vcm_chunk.cpp \
../lammps-dev/src/create_atoms.cpp \
../lammps-dev/src/create_bonds.cpp \
../lammps-dev/src/create_box.cpp \
../lammps-dev/src/delete_atoms.cpp \
../lammps-dev/src/delete_bonds.cpp \
../lammps-dev/src/deprecated.cpp \
../lammps-dev/src/dihedral.cpp \
../lammps-dev/src/dihedral_charmm.cpp \
../lammps-dev/src/dihedral_charmmfsw.cpp \
../lammps-dev/src/dihedral_deprecated.cpp \
../lammps-dev/src/dihedral_harmonic.cpp \
../lammps-dev/src/dihedral_helix.cpp \
../lammps-dev/src/dihedral_hybrid.cpp \
../lammps-dev/src/dihedral_multi_harmonic.cpp \
../lammps-dev/src/dihedral_opls.cpp \
../lammps-dev/src/dihedral_zero.cpp \
../lammps-dev/src/displace_atoms.cpp \
../lammps-dev/src/domain.cpp \
../lammps-dev/src/dump.cpp \
../lammps-dev/src/dump_atom.cpp \
../lammps-dev/src/dump_cfg.cpp \
../lammps-dev/src/dump_custom.cpp \
../lammps-dev/src/dump_dcd.cpp \
../lammps-dev/src/dump_deprecated.cpp \
../lammps-dev/src/dump_image.cpp \
../lammps-dev/src/dump_local.cpp \
../lammps-dev/src/dump_movie.cpp \
../lammps-dev/src/dump_xyz.cpp \
../lammps-dev/src/dynamical_matrix.cpp \
../lammps-dev/src/error.cpp \
../lammps-dev/src/ewald.cpp \
../lammps-dev/src/ewald_dipole.cpp \
../lammps-dev/src/ewald_dipole_spin.cpp \
../lammps-dev/src/ewald_disp.cpp \
../lammps-dev/src/fft3d.cpp \
../lammps-dev/src/fft3d_wrap.cpp \
../lammps-dev/src/finish.cpp \
../lammps-dev/src/fix.cpp \
../lammps-dev/src/fix_adapt.cpp \
../lammps-dev/src/fix_addforce.cpp \
../lammps-dev/src/fix_ave_atom.cpp \
../lammps-dev/src/fix_ave_chunk.cpp \
../lammps-dev/src/fix_ave_correlate.cpp \
../lammps-dev/src/fix_ave_histo.cpp \
../lammps-dev/src/fix_ave_histo_weight.cpp \
../lammps-dev/src/fix_ave_time.cpp \
../lammps-dev/src/fix_aveforce.cpp \
../lammps-dev/src/fix_balance.cpp \
../lammps-dev/src/fix_box_relax.cpp \
../lammps-dev/src/fix_cmap.cpp \
../lammps-dev/src/fix_controller.cpp \
../lammps-dev/src/fix_deform.cpp \
../lammps-dev/src/fix_deprecated.cpp \
../lammps-dev/src/fix_drag.cpp \
../lammps-dev/src/fix_dt_reset.cpp \
../lammps-dev/src/fix_dummy.cpp \
../lammps-dev/src/fix_enforce2d.cpp \
../lammps-dev/src/fix_external.cpp \
../lammps-dev/src/fix_gravity.cpp \
../lammps-dev/src/fix_group.cpp \
../lammps-dev/src/fix_halt.cpp \
../lammps-dev/src/fix_heat.cpp \
../lammps-dev/src/fix_indent.cpp \
../lammps-dev/src/fix_langevin.cpp \
../lammps-dev/src/fix_lineforce.cpp \
../lammps-dev/src/fix_minimize.cpp \
../lammps-dev/src/fix_momentum.cpp \
../lammps-dev/src/fix_move.cpp \
../lammps-dev/src/fix_neigh_history.cpp \
../lammps-dev/src/fix_nh.cpp \
../lammps-dev/src/fix_nh_sphere.cpp \
../lammps-dev/src/fix_nph.cpp \
../lammps-dev/src/fix_nph_sphere.cpp \
../lammps-dev/src/fix_npt.cpp \
../lammps-dev/src/fix_npt_sphere.cpp \
../lammps-dev/src/fix_numdiff.cpp \
../lammps-dev/src/fix_nve.cpp \
../lammps-dev/src/fix_nve_limit.cpp \
../lammps-dev/src/fix_nve_noforce.cpp \
../lammps-dev/src/fix_nve_sphere.cpp \
../lammps-dev/src/fix_nvt.cpp \
../lammps-dev/src/fix_nvt_sllod.cpp \
../lammps-dev/src/fix_nvt_sphere.cpp \
../lammps-dev/src/fix_phonon.cpp \
../lammps-dev/src/fix_planeforce.cpp \
../lammps-dev/src/fix_press_berendsen.cpp \
../lammps-dev/src/fix_print.cpp \
../lammps-dev/src/fix_property_atom.cpp \
../lammps-dev/src/fix_read_restart.cpp \
../lammps-dev/src/fix_recenter.cpp \
../lammps-dev/src/fix_respa.cpp \
../lammps-dev/src/fix_restrain.cpp \
../lammps-dev/src/fix_setforce.cpp \
../lammps-dev/src/fix_spring.cpp \
../lammps-dev/src/fix_spring_chunk.cpp \
../lammps-dev/src/fix_spring_rg.cpp \
../lammps-dev/src/fix_spring_self.cpp \
../lammps-dev/src/fix_store.cpp \
../lammps-dev/src/fix_store_force.cpp \
../lammps-dev/src/fix_store_state.cpp \
../lammps-dev/src/fix_temp_berendsen.cpp \
../lammps-dev/src/fix_temp_csld.cpp \
../lammps-dev/src/fix_temp_csvr.cpp \
../lammps-dev/src/fix_temp_rescale.cpp \
../lammps-dev/src/fix_tmd.cpp \
../lammps-dev/src/fix_tune_kspace.cpp \
../lammps-dev/src/fix_vector.cpp \
../lammps-dev/src/fix_viscous.cpp \
../lammps-dev/src/fix_wall.cpp \
../lammps-dev/src/fix_wall_harmonic.cpp \
../lammps-dev/src/fix_wall_lj1043.cpp \
../lammps-dev/src/fix_wall_lj126.cpp \
../lammps-dev/src/fix_wall_lj93.cpp \
../lammps-dev/src/fix_wall_morse.cpp \
../lammps-dev/src/fix_wall_reflect.cpp \
../lammps-dev/src/fix_wall_region.cpp \
../lammps-dev/src/fmtlib_format.cpp \
../lammps-dev/src/fmtlib_os.cpp \
../lammps-dev/src/force.cpp \
../lammps-dev/src/gridcomm.cpp \
../lammps-dev/src/group.cpp \
../lammps-dev/src/hashlittle.cpp \
../lammps-dev/src/image.cpp \
../lammps-dev/src/imbalance.cpp \
../lammps-dev/src/imbalance_group.cpp \
../lammps-dev/src/imbalance_neigh.cpp \
../lammps-dev/src/imbalance_store.cpp \
../lammps-dev/src/imbalance_time.cpp \
../lammps-dev/src/imbalance_var.cpp \
../lammps-dev/src/improper.cpp \
../lammps-dev/src/improper_cvff.cpp \
../lammps-dev/src/improper_deprecated.cpp \
../lammps-dev/src/improper_harmonic.cpp \
../lammps-dev/src/improper_hybrid.cpp \
../lammps-dev/src/improper_umbrella.cpp \
../lammps-dev/src/improper_zero.cpp \
../lammps-dev/src/info.cpp \
../lammps-dev/src/input.cpp \
../lammps-dev/src/integrate.cpp \
../lammps-dev/src/irregular.cpp \
../lammps-dev/src/kspace.cpp \
../lammps-dev/src/kspace_deprecated.cpp \
../lammps-dev/src/lammps.cpp \
../lammps-dev/src/lattice.cpp \
../lammps-dev/src/library.cpp \
../lammps-dev/src/lmppython.cpp \
../lammps-dev/src/main.cpp \
../lammps-dev/src/math_eigen.cpp \
../lammps-dev/src/math_extra.cpp \
../lammps-dev/src/math_special.cpp \
../lammps-dev/src/memory.cpp \
../lammps-dev/src/min.cpp \
../lammps-dev/src/min_cg.cpp \
../lammps-dev/src/min_fire.cpp \
../lammps-dev/src/min_fire_old.cpp \
../lammps-dev/src/min_hftn.cpp \
../lammps-dev/src/min_linesearch.cpp \
../lammps-dev/src/min_quickmin.cpp \
../lammps-dev/src/min_sd.cpp \
../lammps-dev/src/minimize.cpp \
../lammps-dev/src/modify.cpp \
../lammps-dev/src/molecule.cpp \
../lammps-dev/src/msm.cpp \
../lammps-dev/src/msm_cg.cpp \
../lammps-dev/src/my_page.cpp \
../lammps-dev/src/my_pool_chunk.cpp \
../lammps-dev/src/nbin.cpp \
../lammps-dev/src/nbin_standard.cpp \
../lammps-dev/src/neigh_list.cpp \
../lammps-dev/src/neigh_request.cpp \
../lammps-dev/src/neighbor.cpp \
../lammps-dev/src/npair.cpp \
../lammps-dev/src/npair_copy.cpp \
../lammps-dev/src/npair_full_bin.cpp \
../lammps-dev/src/npair_full_bin_atomonly.cpp \
../lammps-dev/src/npair_full_bin_ghost.cpp \
../lammps-dev/src/npair_full_multi.cpp \
../lammps-dev/src/npair_full_nsq.cpp \
../lammps-dev/src/npair_full_nsq_ghost.cpp \
../lammps-dev/src/npair_half_bin_atomonly_newton.cpp \
../lammps-dev/src/npair_half_bin_newtoff.cpp \
../lammps-dev/src/npair_half_bin_newtoff_ghost.cpp \
../lammps-dev/src/npair_half_bin_newton.cpp \
../lammps-dev/src/npair_half_bin_newton_tri.cpp \
../lammps-dev/src/npair_half_multi_newtoff.cpp \
../lammps-dev/src/npair_half_multi_newton.cpp \
../lammps-dev/src/npair_half_multi_newton_tri.cpp \
../lammps-dev/src/npair_half_nsq_newtoff.cpp \
../lammps-dev/src/npair_half_nsq_newtoff_ghost.cpp \
../lammps-dev/src/npair_half_nsq_newton.cpp \
../lammps-dev/src/npair_half_respa_bin_newtoff.cpp \
../lammps-dev/src/npair_half_respa_bin_newton.cpp \
../lammps-dev/src/npair_half_respa_bin_newton_tri.cpp \
../lammps-dev/src/npair_half_respa_nsq_newtoff.cpp \
../lammps-dev/src/npair_half_respa_nsq_newton.cpp \
../lammps-dev/src/npair_half_size_bin_newtoff.cpp \
../lammps-dev/src/npair_half_size_bin_newton.cpp \
../lammps-dev/src/npair_half_size_bin_newton_tri.cpp \
../lammps-dev/src/npair_half_size_multi_newtoff.cpp \
../lammps-dev/src/npair_half_size_multi_newton.cpp \
../lammps-dev/src/npair_half_size_multi_newton_tri.cpp \
../lammps-dev/src/npair_half_size_nsq_newtoff.cpp \
../lammps-dev/src/npair_half_size_nsq_newton.cpp \
../lammps-dev/src/npair_halffull_newtoff.cpp \
../lammps-dev/src/npair_halffull_newton.cpp \
../lammps-dev/src/npair_skip.cpp \
../lammps-dev/src/npair_skip_respa.cpp \
../lammps-dev/src/npair_skip_size.cpp \
../lammps-dev/src/npair_skip_size_off2on.cpp \
../lammps-dev/src/npair_skip_size_off2on_oneside.cpp \
../lammps-dev/src/nstencil.cpp \
../lammps-dev/src/nstencil_full_bin_2d.cpp \
../lammps-dev/src/nstencil_full_bin_3d.cpp \
../lammps-dev/src/nstencil_full_ghost_bin_2d.cpp \
../lammps-dev/src/nstencil_full_ghost_bin_3d.cpp \
../lammps-dev/src/nstencil_full_multi_2d.cpp \
../lammps-dev/src/nstencil_full_multi_3d.cpp \
../lammps-dev/src/nstencil_half_bin_2d_newtoff.cpp \
../lammps-dev/src/nstencil_half_bin_2d_newton.cpp \
../lammps-dev/src/nstencil_half_bin_2d_newton_tri.cpp \
../lammps-dev/src/nstencil_half_bin_3d_newtoff.cpp \
../lammps-dev/src/nstencil_half_bin_3d_newton.cpp \
../lammps-dev/src/nstencil_half_bin_3d_newton_tri.cpp \
../lammps-dev/src/nstencil_half_ghost_bin_2d_newtoff.cpp \
../lammps-dev/src/nstencil_half_ghost_bin_3d_newtoff.cpp \
../lammps-dev/src/nstencil_half_multi_2d_newtoff.cpp \
../lammps-dev/src/nstencil_half_multi_2d_newton.cpp \
../lammps-dev/src/nstencil_half_multi_2d_newton_tri.cpp \
../lammps-dev/src/nstencil_half_multi_3d_newtoff.cpp \
../lammps-dev/src/nstencil_half_multi_3d_newton.cpp \
../lammps-dev/src/nstencil_half_multi_3d_newton_tri.cpp \
../lammps-dev/src/ntopo.cpp \
../lammps-dev/src/ntopo_angle_all.cpp \
../lammps-dev/src/ntopo_angle_partial.cpp \
../lammps-dev/src/ntopo_angle_template.cpp \
../lammps-dev/src/ntopo_bond_all.cpp \
../lammps-dev/src/ntopo_bond_partial.cpp \
../lammps-dev/src/ntopo_bond_template.cpp \
../lammps-dev/src/ntopo_dihedral_all.cpp \
../lammps-dev/src/ntopo_dihedral_partial.cpp \
../lammps-dev/src/ntopo_dihedral_template.cpp \
../lammps-dev/src/ntopo_improper_all.cpp \
../lammps-dev/src/ntopo_improper_partial.cpp \
../lammps-dev/src/ntopo_improper_template.cpp \
../lammps-dev/src/output.cpp \
../lammps-dev/src/pair.cpp \
../lammps-dev/src/pair_beck.cpp \
../lammps-dev/src/pair_born.cpp \
../lammps-dev/src/pair_born_coul_dsf.cpp \
../lammps-dev/src/pair_born_coul_long.cpp \
../lammps-dev/src/pair_born_coul_msm.cpp \
../lammps-dev/src/pair_born_coul_wolf.cpp \
../lammps-dev/src/pair_buck.cpp \
../lammps-dev/src/pair_buck_coul_cut.cpp \
../lammps-dev/src/pair_buck_coul_long.cpp \
../lammps-dev/src/pair_buck_coul_msm.cpp \
../lammps-dev/src/pair_buck_long_coul_long.cpp \
../lammps-dev/src/pair_coul_cut.cpp \
../lammps-dev/src/pair_coul_debye.cpp \
../lammps-dev/src/pair_coul_dsf.cpp \
../lammps-dev/src/pair_coul_long.cpp \
../lammps-dev/src/pair_coul_msm.cpp \
../lammps-dev/src/pair_coul_streitz.cpp \
../lammps-dev/src/pair_coul_wolf.cpp \
../lammps-dev/src/pair_deprecated.cpp \
../lammps-dev/src/pair_dpd.cpp \
../lammps-dev/src/pair_dpd_tstat.cpp \
../lammps-dev/src/pair_gauss.cpp \
../lammps-dev/src/pair_hbond_dreiding_lj.cpp \
../lammps-dev/src/pair_hbond_dreiding_morse.cpp \
../lammps-dev/src/pair_hybrid.cpp \
../lammps-dev/src/pair_hybrid_overlay.cpp \
../lammps-dev/src/pair_lj96_cut.cpp \
../lammps-dev/src/pair_lj_charmm_coul_charmm.cpp \
../lammps-dev/src/pair_lj_charmm_coul_charmm_implicit.cpp \
../lammps-dev/src/pair_lj_charmm_coul_long.cpp \
../lammps-dev/src/pair_lj_charmm_coul_msm.cpp \
../lammps-dev/src/pair_lj_charmmfsw_coul_charmmfsh.cpp \
../lammps-dev/src/pair_lj_charmmfsw_coul_long.cpp \
../lammps-dev/src/pair_lj_cubic.cpp \
../lammps-dev/src/pair_lj_cut.cpp \
../lammps-dev/src/pair_lj_cut_coul_cut.cpp \
../lammps-dev/src/pair_lj_cut_coul_debye.cpp \
../lammps-dev/src/pair_lj_cut_coul_dsf.cpp \
../lammps-dev/src/pair_lj_cut_coul_long.cpp \
../lammps-dev/src/pair_lj_cut_coul_msm.cpp \
../lammps-dev/src/pair_lj_cut_coul_wolf.cpp \
../lammps-dev/src/pair_lj_cut_tip4p_cut.cpp \
../lammps-dev/src/pair_lj_cut_tip4p_long.cpp \
../lammps-dev/src/pair_lj_expand.cpp \
../lammps-dev/src/pair_lj_gromacs.cpp \
../lammps-dev/src/pair_lj_gromacs_coul_gromacs.cpp \
../lammps-dev/src/pair_lj_long_coul_long.cpp \
../lammps-dev/src/pair_lj_long_tip4p_long.cpp \
../lammps-dev/src/pair_lj_relres.cpp \
../lammps-dev/src/pair_lj_smooth.cpp \
../lammps-dev/src/pair_lj_smooth_linear.cpp \
../lammps-dev/src/pair_mie_cut.cpp \
../lammps-dev/src/pair_morse.cpp \
../lammps-dev/src/pair_soft.cpp \
../lammps-dev/src/pair_table.cpp \
../lammps-dev/src/pair_tip4p_cut.cpp \
../lammps-dev/src/pair_tip4p_long.cpp \
../lammps-dev/src/pair_ufm.cpp \
../lammps-dev/src/pair_yukawa.cpp \
../lammps-dev/src/pair_zbl.cpp \
../lammps-dev/src/pair_zero.cpp \
../lammps-dev/src/potential_file_reader.cpp \
../lammps-dev/src/pppm.cpp \
../lammps-dev/src/pppm_cg.cpp \
../lammps-dev/src/pppm_dipole.cpp \
../lammps-dev/src/pppm_dipole_spin.cpp \
../lammps-dev/src/pppm_disp.cpp \
../lammps-dev/src/pppm_disp_tip4p.cpp \
../lammps-dev/src/pppm_stagger.cpp \
../lammps-dev/src/pppm_tip4p.cpp \
../lammps-dev/src/procmap.cpp \
../lammps-dev/src/random_mars.cpp \
../lammps-dev/src/random_park.cpp \
../lammps-dev/src/rcb.cpp \
../lammps-dev/src/read_data.cpp \
../lammps-dev/src/read_dump.cpp \
../lammps-dev/src/read_restart.cpp \
../lammps-dev/src/reader.cpp \
../lammps-dev/src/reader_native.cpp \
../lammps-dev/src/reader_xyz.cpp \
../lammps-dev/src/region.cpp \
../lammps-dev/src/region_block.cpp \
../lammps-dev/src/region_cone.cpp \
../lammps-dev/src/region_cylinder.cpp \
../lammps-dev/src/region_deprecated.cpp \
../lammps-dev/src/region_intersect.cpp \
../lammps-dev/src/region_plane.cpp \
../lammps-dev/src/region_prism.cpp \
../lammps-dev/src/region_sphere.cpp \
../lammps-dev/src/region_union.cpp \
../lammps-dev/src/remap.cpp \
../lammps-dev/src/remap_wrap.cpp \
../lammps-dev/src/replicate.cpp \
../lammps-dev/src/rerun.cpp \
../lammps-dev/src/reset_atom_ids.cpp \
../lammps-dev/src/reset_ids.cpp \
../lammps-dev/src/reset_mol_ids.cpp \
../lammps-dev/src/respa.cpp \
../lammps-dev/src/run.cpp \
../lammps-dev/src/set.cpp \
../lammps-dev/src/special.cpp \
../lammps-dev/src/table_file_reader.cpp \
../lammps-dev/src/text_file_reader.cpp \
../lammps-dev/src/thermo.cpp \
../lammps-dev/src/third_order.cpp \
../lammps-dev/src/timer.cpp \
../lammps-dev/src/tokenizer.cpp \
../lammps-dev/src/universe.cpp \
../lammps-dev/src/update.cpp \
../lammps-dev/src/utils.cpp \
../lammps-dev/src/variable.cpp \
../lammps-dev/src/velocity.cpp \
../lammps-dev/src/verlet.cpp \
../lammps-dev/src/write_coeff.cpp \
../lammps-dev/src/write_data.cpp \
../lammps-dev/src/write_dump.cpp \
../lammps-dev/src/write_restart.cpp 

OBJS += \
./lammps-dev/src/angle.o \
./lammps-dev/src/angle_charmm.o \
./lammps-dev/src/angle_cosine.o \
./lammps-dev/src/angle_cosine_delta.o \
./lammps-dev/src/angle_cosine_periodic.o \
./lammps-dev/src/angle_cosine_squared.o \
./lammps-dev/src/angle_deprecated.o \
./lammps-dev/src/angle_harmonic.o \
./lammps-dev/src/angle_hybrid.o \
./lammps-dev/src/angle_table.o \
./lammps-dev/src/angle_zero.o \
./lammps-dev/src/arg_info.o \
./lammps-dev/src/atom.o \
./lammps-dev/src/atom_map.o \
./lammps-dev/src/atom_vec.o \
./lammps-dev/src/atom_vec_angle.o \
./lammps-dev/src/atom_vec_atomic.o \
./lammps-dev/src/atom_vec_body.o \
./lammps-dev/src/atom_vec_bond.o \
./lammps-dev/src/atom_vec_charge.o \
./lammps-dev/src/atom_vec_ellipsoid.o \
./lammps-dev/src/atom_vec_full.o \
./lammps-dev/src/atom_vec_hybrid.o \
./lammps-dev/src/atom_vec_line.o \
./lammps-dev/src/atom_vec_molecular.o \
./lammps-dev/src/atom_vec_sphere.o \
./lammps-dev/src/atom_vec_template.o \
./lammps-dev/src/atom_vec_tri.o \
./lammps-dev/src/balance.o \
./lammps-dev/src/body.o \
./lammps-dev/src/bond.o \
./lammps-dev/src/bond_deprecated.o \
./lammps-dev/src/bond_fene.o \
./lammps-dev/src/bond_fene_expand.o \
./lammps-dev/src/bond_gromos.o \
./lammps-dev/src/bond_harmonic.o \
./lammps-dev/src/bond_hybrid.o \
./lammps-dev/src/bond_morse.o \
./lammps-dev/src/bond_nonlinear.o \
./lammps-dev/src/bond_quartic.o \
./lammps-dev/src/bond_table.o \
./lammps-dev/src/bond_zero.o \
./lammps-dev/src/change_box.o \
./lammps-dev/src/citeme.o \
./lammps-dev/src/comm.o \
./lammps-dev/src/comm_brick.o \
./lammps-dev/src/comm_tiled.o \
./lammps-dev/src/compute.o \
./lammps-dev/src/compute_adf.o \
./lammps-dev/src/compute_aggregate_atom.o \
./lammps-dev/src/compute_angle.o \
./lammps-dev/src/compute_angle_local.o \
./lammps-dev/src/compute_angmom_chunk.o \
./lammps-dev/src/compute_bond.o \
./lammps-dev/src/compute_bond_local.o \
./lammps-dev/src/compute_centro_atom.o \
./lammps-dev/src/compute_centroid_stress_atom.o \
./lammps-dev/src/compute_chunk_atom.o \
./lammps-dev/src/compute_chunk_spread_atom.o \
./lammps-dev/src/compute_cluster_atom.o \
./lammps-dev/src/compute_cna_atom.o \
./lammps-dev/src/compute_com.o \
./lammps-dev/src/compute_com_chunk.o \
./lammps-dev/src/compute_contact_atom.o \
./lammps-dev/src/compute_coord_atom.o \
./lammps-dev/src/compute_deprecated.o \
./lammps-dev/src/compute_dihedral.o \
./lammps-dev/src/compute_dihedral_local.o \
./lammps-dev/src/compute_dipole_chunk.o \
./lammps-dev/src/compute_displace_atom.o \
./lammps-dev/src/compute_erotate_sphere.o \
./lammps-dev/src/compute_erotate_sphere_atom.o \
./lammps-dev/src/compute_fragment_atom.o \
./lammps-dev/src/compute_global_atom.o \
./lammps-dev/src/compute_group_group.o \
./lammps-dev/src/compute_gyration.o \
./lammps-dev/src/compute_gyration_chunk.o \
./lammps-dev/src/compute_heat_flux.o \
./lammps-dev/src/compute_hexorder_atom.o \
./lammps-dev/src/compute_improper.o \
./lammps-dev/src/compute_improper_local.o \
./lammps-dev/src/compute_inertia_chunk.o \
./lammps-dev/src/compute_ke.o \
./lammps-dev/src/compute_ke_atom.o \
./lammps-dev/src/compute_msd.o \
./lammps-dev/src/compute_msd_chunk.o \
./lammps-dev/src/compute_omega_chunk.o \
./lammps-dev/src/compute_orientorder_atom.o \
./lammps-dev/src/compute_pair.o \
./lammps-dev/src/compute_pair_local.o \
./lammps-dev/src/compute_pe.o \
./lammps-dev/src/compute_pe_atom.o \
./lammps-dev/src/compute_pressure.o \
./lammps-dev/src/compute_property_atom.o \
./lammps-dev/src/compute_property_chunk.o \
./lammps-dev/src/compute_property_local.o \
./lammps-dev/src/compute_rdf.o \
./lammps-dev/src/compute_reduce.o \
./lammps-dev/src/compute_reduce_chunk.o \
./lammps-dev/src/compute_reduce_region.o \
./lammps-dev/src/compute_slice.o \
./lammps-dev/src/compute_stress_atom.o \
./lammps-dev/src/compute_temp.o \
./lammps-dev/src/compute_temp_chunk.o \
./lammps-dev/src/compute_temp_com.o \
./lammps-dev/src/compute_temp_deform.o \
./lammps-dev/src/compute_temp_partial.o \
./lammps-dev/src/compute_temp_profile.o \
./lammps-dev/src/compute_temp_ramp.o \
./lammps-dev/src/compute_temp_region.o \
./lammps-dev/src/compute_temp_sphere.o \
./lammps-dev/src/compute_torque_chunk.o \
./lammps-dev/src/compute_vacf.o \
./lammps-dev/src/compute_vcm_chunk.o \
./lammps-dev/src/create_atoms.o \
./lammps-dev/src/create_bonds.o \
./lammps-dev/src/create_box.o \
./lammps-dev/src/delete_atoms.o \
./lammps-dev/src/delete_bonds.o \
./lammps-dev/src/deprecated.o \
./lammps-dev/src/dihedral.o \
./lammps-dev/src/dihedral_charmm.o \
./lammps-dev/src/dihedral_charmmfsw.o \
./lammps-dev/src/dihedral_deprecated.o \
./lammps-dev/src/dihedral_harmonic.o \
./lammps-dev/src/dihedral_helix.o \
./lammps-dev/src/dihedral_hybrid.o \
./lammps-dev/src/dihedral_multi_harmonic.o \
./lammps-dev/src/dihedral_opls.o \
./lammps-dev/src/dihedral_zero.o \
./lammps-dev/src/displace_atoms.o \
./lammps-dev/src/domain.o \
./lammps-dev/src/dump.o \
./lammps-dev/src/dump_atom.o \
./lammps-dev/src/dump_cfg.o \
./lammps-dev/src/dump_custom.o \
./lammps-dev/src/dump_dcd.o \
./lammps-dev/src/dump_deprecated.o \
./lammps-dev/src/dump_image.o \
./lammps-dev/src/dump_local.o \
./lammps-dev/src/dump_movie.o \
./lammps-dev/src/dump_xyz.o \
./lammps-dev/src/dynamical_matrix.o \
./lammps-dev/src/error.o \
./lammps-dev/src/ewald.o \
./lammps-dev/src/ewald_dipole.o \
./lammps-dev/src/ewald_dipole_spin.o \
./lammps-dev/src/ewald_disp.o \
./lammps-dev/src/fft3d.o \
./lammps-dev/src/fft3d_wrap.o \
./lammps-dev/src/finish.o \
./lammps-dev/src/fix.o \
./lammps-dev/src/fix_adapt.o \
./lammps-dev/src/fix_addforce.o \
./lammps-dev/src/fix_ave_atom.o \
./lammps-dev/src/fix_ave_chunk.o \
./lammps-dev/src/fix_ave_correlate.o \
./lammps-dev/src/fix_ave_histo.o \
./lammps-dev/src/fix_ave_histo_weight.o \
./lammps-dev/src/fix_ave_time.o \
./lammps-dev/src/fix_aveforce.o \
./lammps-dev/src/fix_balance.o \
./lammps-dev/src/fix_box_relax.o \
./lammps-dev/src/fix_cmap.o \
./lammps-dev/src/fix_controller.o \
./lammps-dev/src/fix_deform.o \
./lammps-dev/src/fix_deprecated.o \
./lammps-dev/src/fix_drag.o \
./lammps-dev/src/fix_dt_reset.o \
./lammps-dev/src/fix_dummy.o \
./lammps-dev/src/fix_enforce2d.o \
./lammps-dev/src/fix_external.o \
./lammps-dev/src/fix_gravity.o \
./lammps-dev/src/fix_group.o \
./lammps-dev/src/fix_halt.o \
./lammps-dev/src/fix_heat.o \
./lammps-dev/src/fix_indent.o \
./lammps-dev/src/fix_langevin.o \
./lammps-dev/src/fix_lineforce.o \
./lammps-dev/src/fix_minimize.o \
./lammps-dev/src/fix_momentum.o \
./lammps-dev/src/fix_move.o \
./lammps-dev/src/fix_neigh_history.o \
./lammps-dev/src/fix_nh.o \
./lammps-dev/src/fix_nh_sphere.o \
./lammps-dev/src/fix_nph.o \
./lammps-dev/src/fix_nph_sphere.o \
./lammps-dev/src/fix_npt.o \
./lammps-dev/src/fix_npt_sphere.o \
./lammps-dev/src/fix_numdiff.o \
./lammps-dev/src/fix_nve.o \
./lammps-dev/src/fix_nve_limit.o \
./lammps-dev/src/fix_nve_noforce.o \
./lammps-dev/src/fix_nve_sphere.o \
./lammps-dev/src/fix_nvt.o \
./lammps-dev/src/fix_nvt_sllod.o \
./lammps-dev/src/fix_nvt_sphere.o \
./lammps-dev/src/fix_phonon.o \
./lammps-dev/src/fix_planeforce.o \
./lammps-dev/src/fix_press_berendsen.o \
./lammps-dev/src/fix_print.o \
./lammps-dev/src/fix_property_atom.o \
./lammps-dev/src/fix_read_restart.o \
./lammps-dev/src/fix_recenter.o \
./lammps-dev/src/fix_respa.o \
./lammps-dev/src/fix_restrain.o \
./lammps-dev/src/fix_setforce.o \
./lammps-dev/src/fix_spring.o \
./lammps-dev/src/fix_spring_chunk.o \
./lammps-dev/src/fix_spring_rg.o \
./lammps-dev/src/fix_spring_self.o \
./lammps-dev/src/fix_store.o \
./lammps-dev/src/fix_store_force.o \
./lammps-dev/src/fix_store_state.o \
./lammps-dev/src/fix_temp_berendsen.o \
./lammps-dev/src/fix_temp_csld.o \
./lammps-dev/src/fix_temp_csvr.o \
./lammps-dev/src/fix_temp_rescale.o \
./lammps-dev/src/fix_tmd.o \
./lammps-dev/src/fix_tune_kspace.o \
./lammps-dev/src/fix_vector.o \
./lammps-dev/src/fix_viscous.o \
./lammps-dev/src/fix_wall.o \
./lammps-dev/src/fix_wall_harmonic.o \
./lammps-dev/src/fix_wall_lj1043.o \
./lammps-dev/src/fix_wall_lj126.o \
./lammps-dev/src/fix_wall_lj93.o \
./lammps-dev/src/fix_wall_morse.o \
./lammps-dev/src/fix_wall_reflect.o \
./lammps-dev/src/fix_wall_region.o \
./lammps-dev/src/fmtlib_format.o \
./lammps-dev/src/fmtlib_os.o \
./lammps-dev/src/force.o \
./lammps-dev/src/gridcomm.o \
./lammps-dev/src/group.o \
./lammps-dev/src/hashlittle.o \
./lammps-dev/src/image.o \
./lammps-dev/src/imbalance.o \
./lammps-dev/src/imbalance_group.o \
./lammps-dev/src/imbalance_neigh.o \
./lammps-dev/src/imbalance_store.o \
./lammps-dev/src/imbalance_time.o \
./lammps-dev/src/imbalance_var.o \
./lammps-dev/src/improper.o \
./lammps-dev/src/improper_cvff.o \
./lammps-dev/src/improper_deprecated.o \
./lammps-dev/src/improper_harmonic.o \
./lammps-dev/src/improper_hybrid.o \
./lammps-dev/src/improper_umbrella.o \
./lammps-dev/src/improper_zero.o \
./lammps-dev/src/info.o \
./lammps-dev/src/input.o \
./lammps-dev/src/integrate.o \
./lammps-dev/src/irregular.o \
./lammps-dev/src/kspace.o \
./lammps-dev/src/kspace_deprecated.o \
./lammps-dev/src/lammps.o \
./lammps-dev/src/lattice.o \
./lammps-dev/src/library.o \
./lammps-dev/src/lmppython.o \
./lammps-dev/src/main.o \
./lammps-dev/src/math_eigen.o \
./lammps-dev/src/math_extra.o \
./lammps-dev/src/math_special.o \
./lammps-dev/src/memory.o \
./lammps-dev/src/min.o \
./lammps-dev/src/min_cg.o \
./lammps-dev/src/min_fire.o \
./lammps-dev/src/min_fire_old.o \
./lammps-dev/src/min_hftn.o \
./lammps-dev/src/min_linesearch.o \
./lammps-dev/src/min_quickmin.o \
./lammps-dev/src/min_sd.o \
./lammps-dev/src/minimize.o \
./lammps-dev/src/modify.o \
./lammps-dev/src/molecule.o \
./lammps-dev/src/msm.o \
./lammps-dev/src/msm_cg.o \
./lammps-dev/src/my_page.o \
./lammps-dev/src/my_pool_chunk.o \
./lammps-dev/src/nbin.o \
./lammps-dev/src/nbin_standard.o \
./lammps-dev/src/neigh_list.o \
./lammps-dev/src/neigh_request.o \
./lammps-dev/src/neighbor.o \
./lammps-dev/src/npair.o \
./lammps-dev/src/npair_copy.o \
./lammps-dev/src/npair_full_bin.o \
./lammps-dev/src/npair_full_bin_atomonly.o \
./lammps-dev/src/npair_full_bin_ghost.o \
./lammps-dev/src/npair_full_multi.o \
./lammps-dev/src/npair_full_nsq.o \
./lammps-dev/src/npair_full_nsq_ghost.o \
./lammps-dev/src/npair_half_bin_atomonly_newton.o \
./lammps-dev/src/npair_half_bin_newtoff.o \
./lammps-dev/src/npair_half_bin_newtoff_ghost.o \
./lammps-dev/src/npair_half_bin_newton.o \
./lammps-dev/src/npair_half_bin_newton_tri.o \
./lammps-dev/src/npair_half_multi_newtoff.o \
./lammps-dev/src/npair_half_multi_newton.o \
./lammps-dev/src/npair_half_multi_newton_tri.o \
./lammps-dev/src/npair_half_nsq_newtoff.o \
./lammps-dev/src/npair_half_nsq_newtoff_ghost.o \
./lammps-dev/src/npair_half_nsq_newton.o \
./lammps-dev/src/npair_half_respa_bin_newtoff.o \
./lammps-dev/src/npair_half_respa_bin_newton.o \
./lammps-dev/src/npair_half_respa_bin_newton_tri.o \
./lammps-dev/src/npair_half_respa_nsq_newtoff.o \
./lammps-dev/src/npair_half_respa_nsq_newton.o \
./lammps-dev/src/npair_half_size_bin_newtoff.o \
./lammps-dev/src/npair_half_size_bin_newton.o \
./lammps-dev/src/npair_half_size_bin_newton_tri.o \
./lammps-dev/src/npair_half_size_multi_newtoff.o \
./lammps-dev/src/npair_half_size_multi_newton.o \
./lammps-dev/src/npair_half_size_multi_newton_tri.o \
./lammps-dev/src/npair_half_size_nsq_newtoff.o \
./lammps-dev/src/npair_half_size_nsq_newton.o \
./lammps-dev/src/npair_halffull_newtoff.o \
./lammps-dev/src/npair_halffull_newton.o \
./lammps-dev/src/npair_skip.o \
./lammps-dev/src/npair_skip_respa.o \
./lammps-dev/src/npair_skip_size.o \
./lammps-dev/src/npair_skip_size_off2on.o \
./lammps-dev/src/npair_skip_size_off2on_oneside.o \
./lammps-dev/src/nstencil.o \
./lammps-dev/src/nstencil_full_bin_2d.o \
./lammps-dev/src/nstencil_full_bin_3d.o \
./lammps-dev/src/nstencil_full_ghost_bin_2d.o \
./lammps-dev/src/nstencil_full_ghost_bin_3d.o \
./lammps-dev/src/nstencil_full_multi_2d.o \
./lammps-dev/src/nstencil_full_multi_3d.o \
./lammps-dev/src/nstencil_half_bin_2d_newtoff.o \
./lammps-dev/src/nstencil_half_bin_2d_newton.o \
./lammps-dev/src/nstencil_half_bin_2d_newton_tri.o \
./lammps-dev/src/nstencil_half_bin_3d_newtoff.o \
./lammps-dev/src/nstencil_half_bin_3d_newton.o \
./lammps-dev/src/nstencil_half_bin_3d_newton_tri.o \
./lammps-dev/src/nstencil_half_ghost_bin_2d_newtoff.o \
./lammps-dev/src/nstencil_half_ghost_bin_3d_newtoff.o \
./lammps-dev/src/nstencil_half_multi_2d_newtoff.o \
./lammps-dev/src/nstencil_half_multi_2d_newton.o \
./lammps-dev/src/nstencil_half_multi_2d_newton_tri.o \
./lammps-dev/src/nstencil_half_multi_3d_newtoff.o \
./lammps-dev/src/nstencil_half_multi_3d_newton.o \
./lammps-dev/src/nstencil_half_multi_3d_newton_tri.o \
./lammps-dev/src/ntopo.o \
./lammps-dev/src/ntopo_angle_all.o \
./lammps-dev/src/ntopo_angle_partial.o \
./lammps-dev/src/ntopo_angle_template.o \
./lammps-dev/src/ntopo_bond_all.o \
./lammps-dev/src/ntopo_bond_partial.o \
./lammps-dev/src/ntopo_bond_template.o \
./lammps-dev/src/ntopo_dihedral_all.o \
./lammps-dev/src/ntopo_dihedral_partial.o \
./lammps-dev/src/ntopo_dihedral_template.o \
./lammps-dev/src/ntopo_improper_all.o \
./lammps-dev/src/ntopo_improper_partial.o \
./lammps-dev/src/ntopo_improper_template.o \
./lammps-dev/src/output.o \
./lammps-dev/src/pair.o \
./lammps-dev/src/pair_beck.o \
./lammps-dev/src/pair_born.o \
./lammps-dev/src/pair_born_coul_dsf.o \
./lammps-dev/src/pair_born_coul_long.o \
./lammps-dev/src/pair_born_coul_msm.o \
./lammps-dev/src/pair_born_coul_wolf.o \
./lammps-dev/src/pair_buck.o \
./lammps-dev/src/pair_buck_coul_cut.o \
./lammps-dev/src/pair_buck_coul_long.o \
./lammps-dev/src/pair_buck_coul_msm.o \
./lammps-dev/src/pair_buck_long_coul_long.o \
./lammps-dev/src/pair_coul_cut.o \
./lammps-dev/src/pair_coul_debye.o \
./lammps-dev/src/pair_coul_dsf.o \
./lammps-dev/src/pair_coul_long.o \
./lammps-dev/src/pair_coul_msm.o \
./lammps-dev/src/pair_coul_streitz.o \
./lammps-dev/src/pair_coul_wolf.o \
./lammps-dev/src/pair_deprecated.o \
./lammps-dev/src/pair_dpd.o \
./lammps-dev/src/pair_dpd_tstat.o \
./lammps-dev/src/pair_gauss.o \
./lammps-dev/src/pair_hbond_dreiding_lj.o \
./lammps-dev/src/pair_hbond_dreiding_morse.o \
./lammps-dev/src/pair_hybrid.o \
./lammps-dev/src/pair_hybrid_overlay.o \
./lammps-dev/src/pair_lj96_cut.o \
./lammps-dev/src/pair_lj_charmm_coul_charmm.o \
./lammps-dev/src/pair_lj_charmm_coul_charmm_implicit.o \
./lammps-dev/src/pair_lj_charmm_coul_long.o \
./lammps-dev/src/pair_lj_charmm_coul_msm.o \
./lammps-dev/src/pair_lj_charmmfsw_coul_charmmfsh.o \
./lammps-dev/src/pair_lj_charmmfsw_coul_long.o \
./lammps-dev/src/pair_lj_cubic.o \
./lammps-dev/src/pair_lj_cut.o \
./lammps-dev/src/pair_lj_cut_coul_cut.o \
./lammps-dev/src/pair_lj_cut_coul_debye.o \
./lammps-dev/src/pair_lj_cut_coul_dsf.o \
./lammps-dev/src/pair_lj_cut_coul_long.o \
./lammps-dev/src/pair_lj_cut_coul_msm.o \
./lammps-dev/src/pair_lj_cut_coul_wolf.o \
./lammps-dev/src/pair_lj_cut_tip4p_cut.o \
./lammps-dev/src/pair_lj_cut_tip4p_long.o \
./lammps-dev/src/pair_lj_expand.o \
./lammps-dev/src/pair_lj_gromacs.o \
./lammps-dev/src/pair_lj_gromacs_coul_gromacs.o \
./lammps-dev/src/pair_lj_long_coul_long.o \
./lammps-dev/src/pair_lj_long_tip4p_long.o \
./lammps-dev/src/pair_lj_relres.o \
./lammps-dev/src/pair_lj_smooth.o \
./lammps-dev/src/pair_lj_smooth_linear.o \
./lammps-dev/src/pair_mie_cut.o \
./lammps-dev/src/pair_morse.o \
./lammps-dev/src/pair_soft.o \
./lammps-dev/src/pair_table.o \
./lammps-dev/src/pair_tip4p_cut.o \
./lammps-dev/src/pair_tip4p_long.o \
./lammps-dev/src/pair_ufm.o \
./lammps-dev/src/pair_yukawa.o \
./lammps-dev/src/pair_zbl.o \
./lammps-dev/src/pair_zero.o \
./lammps-dev/src/potential_file_reader.o \
./lammps-dev/src/pppm.o \
./lammps-dev/src/pppm_cg.o \
./lammps-dev/src/pppm_dipole.o \
./lammps-dev/src/pppm_dipole_spin.o \
./lammps-dev/src/pppm_disp.o \
./lammps-dev/src/pppm_disp_tip4p.o \
./lammps-dev/src/pppm_stagger.o \
./lammps-dev/src/pppm_tip4p.o \
./lammps-dev/src/procmap.o \
./lammps-dev/src/random_mars.o \
./lammps-dev/src/random_park.o \
./lammps-dev/src/rcb.o \
./lammps-dev/src/read_data.o \
./lammps-dev/src/read_dump.o \
./lammps-dev/src/read_restart.o \
./lammps-dev/src/reader.o \
./lammps-dev/src/reader_native.o \
./lammps-dev/src/reader_xyz.o \
./lammps-dev/src/region.o \
./lammps-dev/src/region_block.o \
./lammps-dev/src/region_cone.o \
./lammps-dev/src/region_cylinder.o \
./lammps-dev/src/region_deprecated.o \
./lammps-dev/src/region_intersect.o \
./lammps-dev/src/region_plane.o \
./lammps-dev/src/region_prism.o \
./lammps-dev/src/region_sphere.o \
./lammps-dev/src/region_union.o \
./lammps-dev/src/remap.o \
./lammps-dev/src/remap_wrap.o \
./lammps-dev/src/replicate.o \
./lammps-dev/src/rerun.o \
./lammps-dev/src/reset_atom_ids.o \
./lammps-dev/src/reset_ids.o \
./lammps-dev/src/reset_mol_ids.o \
./lammps-dev/src/respa.o \
./lammps-dev/src/run.o \
./lammps-dev/src/set.o \
./lammps-dev/src/special.o \
./lammps-dev/src/table_file_reader.o \
./lammps-dev/src/text_file_reader.o \
./lammps-dev/src/thermo.o \
./lammps-dev/src/third_order.o \
./lammps-dev/src/timer.o \
./lammps-dev/src/tokenizer.o \
./lammps-dev/src/universe.o \
./lammps-dev/src/update.o \
./lammps-dev/src/utils.o \
./lammps-dev/src/variable.o \
./lammps-dev/src/velocity.o \
./lammps-dev/src/verlet.o \
./lammps-dev/src/write_coeff.o \
./lammps-dev/src/write_data.o \
./lammps-dev/src/write_dump.o \
./lammps-dev/src/write_restart.o 

CPP_DEPS += \
./lammps-dev/src/angle.d \
./lammps-dev/src/angle_charmm.d \
./lammps-dev/src/angle_cosine.d \
./lammps-dev/src/angle_cosine_delta.d \
./lammps-dev/src/angle_cosine_periodic.d \
./lammps-dev/src/angle_cosine_squared.d \
./lammps-dev/src/angle_deprecated.d \
./lammps-dev/src/angle_harmonic.d \
./lammps-dev/src/angle_hybrid.d \
./lammps-dev/src/angle_table.d \
./lammps-dev/src/angle_zero.d \
./lammps-dev/src/arg_info.d \
./lammps-dev/src/atom.d \
./lammps-dev/src/atom_map.d \
./lammps-dev/src/atom_vec.d \
./lammps-dev/src/atom_vec_angle.d \
./lammps-dev/src/atom_vec_atomic.d \
./lammps-dev/src/atom_vec_body.d \
./lammps-dev/src/atom_vec_bond.d \
./lammps-dev/src/atom_vec_charge.d \
./lammps-dev/src/atom_vec_ellipsoid.d \
./lammps-dev/src/atom_vec_full.d \
./lammps-dev/src/atom_vec_hybrid.d \
./lammps-dev/src/atom_vec_line.d \
./lammps-dev/src/atom_vec_molecular.d \
./lammps-dev/src/atom_vec_sphere.d \
./lammps-dev/src/atom_vec_template.d \
./lammps-dev/src/atom_vec_tri.d \
./lammps-dev/src/balance.d \
./lammps-dev/src/body.d \
./lammps-dev/src/bond.d \
./lammps-dev/src/bond_deprecated.d \
./lammps-dev/src/bond_fene.d \
./lammps-dev/src/bond_fene_expand.d \
./lammps-dev/src/bond_gromos.d \
./lammps-dev/src/bond_harmonic.d \
./lammps-dev/src/bond_hybrid.d \
./lammps-dev/src/bond_morse.d \
./lammps-dev/src/bond_nonlinear.d \
./lammps-dev/src/bond_quartic.d \
./lammps-dev/src/bond_table.d \
./lammps-dev/src/bond_zero.d \
./lammps-dev/src/change_box.d \
./lammps-dev/src/citeme.d \
./lammps-dev/src/comm.d \
./lammps-dev/src/comm_brick.d \
./lammps-dev/src/comm_tiled.d \
./lammps-dev/src/compute.d \
./lammps-dev/src/compute_adf.d \
./lammps-dev/src/compute_aggregate_atom.d \
./lammps-dev/src/compute_angle.d \
./lammps-dev/src/compute_angle_local.d \
./lammps-dev/src/compute_angmom_chunk.d \
./lammps-dev/src/compute_bond.d \
./lammps-dev/src/compute_bond_local.d \
./lammps-dev/src/compute_centro_atom.d \
./lammps-dev/src/compute_centroid_stress_atom.d \
./lammps-dev/src/compute_chunk_atom.d \
./lammps-dev/src/compute_chunk_spread_atom.d \
./lammps-dev/src/compute_cluster_atom.d \
./lammps-dev/src/compute_cna_atom.d \
./lammps-dev/src/compute_com.d \
./lammps-dev/src/compute_com_chunk.d \
./lammps-dev/src/compute_contact_atom.d \
./lammps-dev/src/compute_coord_atom.d \
./lammps-dev/src/compute_deprecated.d \
./lammps-dev/src/compute_dihedral.d \
./lammps-dev/src/compute_dihedral_local.d \
./lammps-dev/src/compute_dipole_chunk.d \
./lammps-dev/src/compute_displace_atom.d \
./lammps-dev/src/compute_erotate_sphere.d \
./lammps-dev/src/compute_erotate_sphere_atom.d \
./lammps-dev/src/compute_fragment_atom.d \
./lammps-dev/src/compute_global_atom.d \
./lammps-dev/src/compute_group_group.d \
./lammps-dev/src/compute_gyration.d \
./lammps-dev/src/compute_gyration_chunk.d \
./lammps-dev/src/compute_heat_flux.d \
./lammps-dev/src/compute_hexorder_atom.d \
./lammps-dev/src/compute_improper.d \
./lammps-dev/src/compute_improper_local.d \
./lammps-dev/src/compute_inertia_chunk.d \
./lammps-dev/src/compute_ke.d \
./lammps-dev/src/compute_ke_atom.d \
./lammps-dev/src/compute_msd.d \
./lammps-dev/src/compute_msd_chunk.d \
./lammps-dev/src/compute_omega_chunk.d \
./lammps-dev/src/compute_orientorder_atom.d \
./lammps-dev/src/compute_pair.d \
./lammps-dev/src/compute_pair_local.d \
./lammps-dev/src/compute_pe.d \
./lammps-dev/src/compute_pe_atom.d \
./lammps-dev/src/compute_pressure.d \
./lammps-dev/src/compute_property_atom.d \
./lammps-dev/src/compute_property_chunk.d \
./lammps-dev/src/compute_property_local.d \
./lammps-dev/src/compute_rdf.d \
./lammps-dev/src/compute_reduce.d \
./lammps-dev/src/compute_reduce_chunk.d \
./lammps-dev/src/compute_reduce_region.d \
./lammps-dev/src/compute_slice.d \
./lammps-dev/src/compute_stress_atom.d \
./lammps-dev/src/compute_temp.d \
./lammps-dev/src/compute_temp_chunk.d \
./lammps-dev/src/compute_temp_com.d \
./lammps-dev/src/compute_temp_deform.d \
./lammps-dev/src/compute_temp_partial.d \
./lammps-dev/src/compute_temp_profile.d \
./lammps-dev/src/compute_temp_ramp.d \
./lammps-dev/src/compute_temp_region.d \
./lammps-dev/src/compute_temp_sphere.d \
./lammps-dev/src/compute_torque_chunk.d \
./lammps-dev/src/compute_vacf.d \
./lammps-dev/src/compute_vcm_chunk.d \
./lammps-dev/src/create_atoms.d \
./lammps-dev/src/create_bonds.d \
./lammps-dev/src/create_box.d \
./lammps-dev/src/delete_atoms.d \
./lammps-dev/src/delete_bonds.d \
./lammps-dev/src/deprecated.d \
./lammps-dev/src/dihedral.d \
./lammps-dev/src/dihedral_charmm.d \
./lammps-dev/src/dihedral_charmmfsw.d \
./lammps-dev/src/dihedral_deprecated.d \
./lammps-dev/src/dihedral_harmonic.d \
./lammps-dev/src/dihedral_helix.d \
./lammps-dev/src/dihedral_hybrid.d \
./lammps-dev/src/dihedral_multi_harmonic.d \
./lammps-dev/src/dihedral_opls.d \
./lammps-dev/src/dihedral_zero.d \
./lammps-dev/src/displace_atoms.d \
./lammps-dev/src/domain.d \
./lammps-dev/src/dump.d \
./lammps-dev/src/dump_atom.d \
./lammps-dev/src/dump_cfg.d \
./lammps-dev/src/dump_custom.d \
./lammps-dev/src/dump_dcd.d \
./lammps-dev/src/dump_deprecated.d \
./lammps-dev/src/dump_image.d \
./lammps-dev/src/dump_local.d \
./lammps-dev/src/dump_movie.d \
./lammps-dev/src/dump_xyz.d \
./lammps-dev/src/dynamical_matrix.d \
./lammps-dev/src/error.d \
./lammps-dev/src/ewald.d \
./lammps-dev/src/ewald_dipole.d \
./lammps-dev/src/ewald_dipole_spin.d \
./lammps-dev/src/ewald_disp.d \
./lammps-dev/src/fft3d.d \
./lammps-dev/src/fft3d_wrap.d \
./lammps-dev/src/finish.d \
./lammps-dev/src/fix.d \
./lammps-dev/src/fix_adapt.d \
./lammps-dev/src/fix_addforce.d \
./lammps-dev/src/fix_ave_atom.d \
./lammps-dev/src/fix_ave_chunk.d \
./lammps-dev/src/fix_ave_correlate.d \
./lammps-dev/src/fix_ave_histo.d \
./lammps-dev/src/fix_ave_histo_weight.d \
./lammps-dev/src/fix_ave_time.d \
./lammps-dev/src/fix_aveforce.d \
./lammps-dev/src/fix_balance.d \
./lammps-dev/src/fix_box_relax.d \
./lammps-dev/src/fix_cmap.d \
./lammps-dev/src/fix_controller.d \
./lammps-dev/src/fix_deform.d \
./lammps-dev/src/fix_deprecated.d \
./lammps-dev/src/fix_drag.d \
./lammps-dev/src/fix_dt_reset.d \
./lammps-dev/src/fix_dummy.d \
./lammps-dev/src/fix_enforce2d.d \
./lammps-dev/src/fix_external.d \
./lammps-dev/src/fix_gravity.d \
./lammps-dev/src/fix_group.d \
./lammps-dev/src/fix_halt.d \
./lammps-dev/src/fix_heat.d \
./lammps-dev/src/fix_indent.d \
./lammps-dev/src/fix_langevin.d \
./lammps-dev/src/fix_lineforce.d \
./lammps-dev/src/fix_minimize.d \
./lammps-dev/src/fix_momentum.d \
./lammps-dev/src/fix_move.d \
./lammps-dev/src/fix_neigh_history.d \
./lammps-dev/src/fix_nh.d \
./lammps-dev/src/fix_nh_sphere.d \
./lammps-dev/src/fix_nph.d \
./lammps-dev/src/fix_nph_sphere.d \
./lammps-dev/src/fix_npt.d \
./lammps-dev/src/fix_npt_sphere.d \
./lammps-dev/src/fix_numdiff.d \
./lammps-dev/src/fix_nve.d \
./lammps-dev/src/fix_nve_limit.d \
./lammps-dev/src/fix_nve_noforce.d \
./lammps-dev/src/fix_nve_sphere.d \
./lammps-dev/src/fix_nvt.d \
./lammps-dev/src/fix_nvt_sllod.d \
./lammps-dev/src/fix_nvt_sphere.d \
./lammps-dev/src/fix_phonon.d \
./lammps-dev/src/fix_planeforce.d \
./lammps-dev/src/fix_press_berendsen.d \
./lammps-dev/src/fix_print.d \
./lammps-dev/src/fix_property_atom.d \
./lammps-dev/src/fix_read_restart.d \
./lammps-dev/src/fix_recenter.d \
./lammps-dev/src/fix_respa.d \
./lammps-dev/src/fix_restrain.d \
./lammps-dev/src/fix_setforce.d \
./lammps-dev/src/fix_spring.d \
./lammps-dev/src/fix_spring_chunk.d \
./lammps-dev/src/fix_spring_rg.d \
./lammps-dev/src/fix_spring_self.d \
./lammps-dev/src/fix_store.d \
./lammps-dev/src/fix_store_force.d \
./lammps-dev/src/fix_store_state.d \
./lammps-dev/src/fix_temp_berendsen.d \
./lammps-dev/src/fix_temp_csld.d \
./lammps-dev/src/fix_temp_csvr.d \
./lammps-dev/src/fix_temp_rescale.d \
./lammps-dev/src/fix_tmd.d \
./lammps-dev/src/fix_tune_kspace.d \
./lammps-dev/src/fix_vector.d \
./lammps-dev/src/fix_viscous.d \
./lammps-dev/src/fix_wall.d \
./lammps-dev/src/fix_wall_harmonic.d \
./lammps-dev/src/fix_wall_lj1043.d \
./lammps-dev/src/fix_wall_lj126.d \
./lammps-dev/src/fix_wall_lj93.d \
./lammps-dev/src/fix_wall_morse.d \
./lammps-dev/src/fix_wall_reflect.d \
./lammps-dev/src/fix_wall_region.d \
./lammps-dev/src/fmtlib_format.d \
./lammps-dev/src/fmtlib_os.d \
./lammps-dev/src/force.d \
./lammps-dev/src/gridcomm.d \
./lammps-dev/src/group.d \
./lammps-dev/src/hashlittle.d \
./lammps-dev/src/image.d \
./lammps-dev/src/imbalance.d \
./lammps-dev/src/imbalance_group.d \
./lammps-dev/src/imbalance_neigh.d \
./lammps-dev/src/imbalance_store.d \
./lammps-dev/src/imbalance_time.d \
./lammps-dev/src/imbalance_var.d \
./lammps-dev/src/improper.d \
./lammps-dev/src/improper_cvff.d \
./lammps-dev/src/improper_deprecated.d \
./lammps-dev/src/improper_harmonic.d \
./lammps-dev/src/improper_hybrid.d \
./lammps-dev/src/improper_umbrella.d \
./lammps-dev/src/improper_zero.d \
./lammps-dev/src/info.d \
./lammps-dev/src/input.d \
./lammps-dev/src/integrate.d \
./lammps-dev/src/irregular.d \
./lammps-dev/src/kspace.d \
./lammps-dev/src/kspace_deprecated.d \
./lammps-dev/src/lammps.d \
./lammps-dev/src/lattice.d \
./lammps-dev/src/library.d \
./lammps-dev/src/lmppython.d \
./lammps-dev/src/main.d \
./lammps-dev/src/math_eigen.d \
./lammps-dev/src/math_extra.d \
./lammps-dev/src/math_special.d \
./lammps-dev/src/memory.d \
./lammps-dev/src/min.d \
./lammps-dev/src/min_cg.d \
./lammps-dev/src/min_fire.d \
./lammps-dev/src/min_fire_old.d \
./lammps-dev/src/min_hftn.d \
./lammps-dev/src/min_linesearch.d \
./lammps-dev/src/min_quickmin.d \
./lammps-dev/src/min_sd.d \
./lammps-dev/src/minimize.d \
./lammps-dev/src/modify.d \
./lammps-dev/src/molecule.d \
./lammps-dev/src/msm.d \
./lammps-dev/src/msm_cg.d \
./lammps-dev/src/my_page.d \
./lammps-dev/src/my_pool_chunk.d \
./lammps-dev/src/nbin.d \
./lammps-dev/src/nbin_standard.d \
./lammps-dev/src/neigh_list.d \
./lammps-dev/src/neigh_request.d \
./lammps-dev/src/neighbor.d \
./lammps-dev/src/npair.d \
./lammps-dev/src/npair_copy.d \
./lammps-dev/src/npair_full_bin.d \
./lammps-dev/src/npair_full_bin_atomonly.d \
./lammps-dev/src/npair_full_bin_ghost.d \
./lammps-dev/src/npair_full_multi.d \
./lammps-dev/src/npair_full_nsq.d \
./lammps-dev/src/npair_full_nsq_ghost.d \
./lammps-dev/src/npair_half_bin_atomonly_newton.d \
./lammps-dev/src/npair_half_bin_newtoff.d \
./lammps-dev/src/npair_half_bin_newtoff_ghost.d \
./lammps-dev/src/npair_half_bin_newton.d \
./lammps-dev/src/npair_half_bin_newton_tri.d \
./lammps-dev/src/npair_half_multi_newtoff.d \
./lammps-dev/src/npair_half_multi_newton.d \
./lammps-dev/src/npair_half_multi_newton_tri.d \
./lammps-dev/src/npair_half_nsq_newtoff.d \
./lammps-dev/src/npair_half_nsq_newtoff_ghost.d \
./lammps-dev/src/npair_half_nsq_newton.d \
./lammps-dev/src/npair_half_respa_bin_newtoff.d \
./lammps-dev/src/npair_half_respa_bin_newton.d \
./lammps-dev/src/npair_half_respa_bin_newton_tri.d \
./lammps-dev/src/npair_half_respa_nsq_newtoff.d \
./lammps-dev/src/npair_half_respa_nsq_newton.d \
./lammps-dev/src/npair_half_size_bin_newtoff.d \
./lammps-dev/src/npair_half_size_bin_newton.d \
./lammps-dev/src/npair_half_size_bin_newton_tri.d \
./lammps-dev/src/npair_half_size_multi_newtoff.d \
./lammps-dev/src/npair_half_size_multi_newton.d \
./lammps-dev/src/npair_half_size_multi_newton_tri.d \
./lammps-dev/src/npair_half_size_nsq_newtoff.d \
./lammps-dev/src/npair_half_size_nsq_newton.d \
./lammps-dev/src/npair_halffull_newtoff.d \
./lammps-dev/src/npair_halffull_newton.d \
./lammps-dev/src/npair_skip.d \
./lammps-dev/src/npair_skip_respa.d \
./lammps-dev/src/npair_skip_size.d \
./lammps-dev/src/npair_skip_size_off2on.d \
./lammps-dev/src/npair_skip_size_off2on_oneside.d \
./lammps-dev/src/nstencil.d \
./lammps-dev/src/nstencil_full_bin_2d.d \
./lammps-dev/src/nstencil_full_bin_3d.d \
./lammps-dev/src/nstencil_full_ghost_bin_2d.d \
./lammps-dev/src/nstencil_full_ghost_bin_3d.d \
./lammps-dev/src/nstencil_full_multi_2d.d \
./lammps-dev/src/nstencil_full_multi_3d.d \
./lammps-dev/src/nstencil_half_bin_2d_newtoff.d \
./lammps-dev/src/nstencil_half_bin_2d_newton.d \
./lammps-dev/src/nstencil_half_bin_2d_newton_tri.d \
./lammps-dev/src/nstencil_half_bin_3d_newtoff.d \
./lammps-dev/src/nstencil_half_bin_3d_newton.d \
./lammps-dev/src/nstencil_half_bin_3d_newton_tri.d \
./lammps-dev/src/nstencil_half_ghost_bin_2d_newtoff.d \
./lammps-dev/src/nstencil_half_ghost_bin_3d_newtoff.d \
./lammps-dev/src/nstencil_half_multi_2d_newtoff.d \
./lammps-dev/src/nstencil_half_multi_2d_newton.d \
./lammps-dev/src/nstencil_half_multi_2d_newton_tri.d \
./lammps-dev/src/nstencil_half_multi_3d_newtoff.d \
./lammps-dev/src/nstencil_half_multi_3d_newton.d \
./lammps-dev/src/nstencil_half_multi_3d_newton_tri.d \
./lammps-dev/src/ntopo.d \
./lammps-dev/src/ntopo_angle_all.d \
./lammps-dev/src/ntopo_angle_partial.d \
./lammps-dev/src/ntopo_angle_template.d \
./lammps-dev/src/ntopo_bond_all.d \
./lammps-dev/src/ntopo_bond_partial.d \
./lammps-dev/src/ntopo_bond_template.d \
./lammps-dev/src/ntopo_dihedral_all.d \
./lammps-dev/src/ntopo_dihedral_partial.d \
./lammps-dev/src/ntopo_dihedral_template.d \
./lammps-dev/src/ntopo_improper_all.d \
./lammps-dev/src/ntopo_improper_partial.d \
./lammps-dev/src/ntopo_improper_template.d \
./lammps-dev/src/output.d \
./lammps-dev/src/pair.d \
./lammps-dev/src/pair_beck.d \
./lammps-dev/src/pair_born.d \
./lammps-dev/src/pair_born_coul_dsf.d \
./lammps-dev/src/pair_born_coul_long.d \
./lammps-dev/src/pair_born_coul_msm.d \
./lammps-dev/src/pair_born_coul_wolf.d \
./lammps-dev/src/pair_buck.d \
./lammps-dev/src/pair_buck_coul_cut.d \
./lammps-dev/src/pair_buck_coul_long.d \
./lammps-dev/src/pair_buck_coul_msm.d \
./lammps-dev/src/pair_buck_long_coul_long.d \
./lammps-dev/src/pair_coul_cut.d \
./lammps-dev/src/pair_coul_debye.d \
./lammps-dev/src/pair_coul_dsf.d \
./lammps-dev/src/pair_coul_long.d \
./lammps-dev/src/pair_coul_msm.d \
./lammps-dev/src/pair_coul_streitz.d \
./lammps-dev/src/pair_coul_wolf.d \
./lammps-dev/src/pair_deprecated.d \
./lammps-dev/src/pair_dpd.d \
./lammps-dev/src/pair_dpd_tstat.d \
./lammps-dev/src/pair_gauss.d \
./lammps-dev/src/pair_hbond_dreiding_lj.d \
./lammps-dev/src/pair_hbond_dreiding_morse.d \
./lammps-dev/src/pair_hybrid.d \
./lammps-dev/src/pair_hybrid_overlay.d \
./lammps-dev/src/pair_lj96_cut.d \
./lammps-dev/src/pair_lj_charmm_coul_charmm.d \
./lammps-dev/src/pair_lj_charmm_coul_charmm_implicit.d \
./lammps-dev/src/pair_lj_charmm_coul_long.d \
./lammps-dev/src/pair_lj_charmm_coul_msm.d \
./lammps-dev/src/pair_lj_charmmfsw_coul_charmmfsh.d \
./lammps-dev/src/pair_lj_charmmfsw_coul_long.d \
./lammps-dev/src/pair_lj_cubic.d \
./lammps-dev/src/pair_lj_cut.d \
./lammps-dev/src/pair_lj_cut_coul_cut.d \
./lammps-dev/src/pair_lj_cut_coul_debye.d \
./lammps-dev/src/pair_lj_cut_coul_dsf.d \
./lammps-dev/src/pair_lj_cut_coul_long.d \
./lammps-dev/src/pair_lj_cut_coul_msm.d \
./lammps-dev/src/pair_lj_cut_coul_wolf.d \
./lammps-dev/src/pair_lj_cut_tip4p_cut.d \
./lammps-dev/src/pair_lj_cut_tip4p_long.d \
./lammps-dev/src/pair_lj_expand.d \
./lammps-dev/src/pair_lj_gromacs.d \
./lammps-dev/src/pair_lj_gromacs_coul_gromacs.d \
./lammps-dev/src/pair_lj_long_coul_long.d \
./lammps-dev/src/pair_lj_long_tip4p_long.d \
./lammps-dev/src/pair_lj_relres.d \
./lammps-dev/src/pair_lj_smooth.d \
./lammps-dev/src/pair_lj_smooth_linear.d \
./lammps-dev/src/pair_mie_cut.d \
./lammps-dev/src/pair_morse.d \
./lammps-dev/src/pair_soft.d \
./lammps-dev/src/pair_table.d \
./lammps-dev/src/pair_tip4p_cut.d \
./lammps-dev/src/pair_tip4p_long.d \
./lammps-dev/src/pair_ufm.d \
./lammps-dev/src/pair_yukawa.d \
./lammps-dev/src/pair_zbl.d \
./lammps-dev/src/pair_zero.d \
./lammps-dev/src/potential_file_reader.d \
./lammps-dev/src/pppm.d \
./lammps-dev/src/pppm_cg.d \
./lammps-dev/src/pppm_dipole.d \
./lammps-dev/src/pppm_dipole_spin.d \
./lammps-dev/src/pppm_disp.d \
./lammps-dev/src/pppm_disp_tip4p.d \
./lammps-dev/src/pppm_stagger.d \
./lammps-dev/src/pppm_tip4p.d \
./lammps-dev/src/procmap.d \
./lammps-dev/src/random_mars.d \
./lammps-dev/src/random_park.d \
./lammps-dev/src/rcb.d \
./lammps-dev/src/read_data.d \
./lammps-dev/src/read_dump.d \
./lammps-dev/src/read_restart.d \
./lammps-dev/src/reader.d \
./lammps-dev/src/reader_native.d \
./lammps-dev/src/reader_xyz.d \
./lammps-dev/src/region.d \
./lammps-dev/src/region_block.d \
./lammps-dev/src/region_cone.d \
./lammps-dev/src/region_cylinder.d \
./lammps-dev/src/region_deprecated.d \
./lammps-dev/src/region_intersect.d \
./lammps-dev/src/region_plane.d \
./lammps-dev/src/region_prism.d \
./lammps-dev/src/region_sphere.d \
./lammps-dev/src/region_union.d \
./lammps-dev/src/remap.d \
./lammps-dev/src/remap_wrap.d \
./lammps-dev/src/replicate.d \
./lammps-dev/src/rerun.d \
./lammps-dev/src/reset_atom_ids.d \
./lammps-dev/src/reset_ids.d \
./lammps-dev/src/reset_mol_ids.d \
./lammps-dev/src/respa.d \
./lammps-dev/src/run.d \
./lammps-dev/src/set.d \
./lammps-dev/src/special.d \
./lammps-dev/src/table_file_reader.d \
./lammps-dev/src/text_file_reader.d \
./lammps-dev/src/thermo.d \
./lammps-dev/src/third_order.d \
./lammps-dev/src/timer.d \
./lammps-dev/src/tokenizer.d \
./lammps-dev/src/universe.d \
./lammps-dev/src/update.d \
./lammps-dev/src/utils.d \
./lammps-dev/src/variable.d \
./lammps-dev/src/velocity.d \
./lammps-dev/src/verlet.d \
./lammps-dev/src/write_coeff.d \
./lammps-dev/src/write_data.d \
./lammps-dev/src/write_dump.d \
./lammps-dev/src/write_restart.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/src/%.o: ../lammps-dev/src/%.cpp lammps-dev/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


