################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/src/KOKKOS/angle_charmm_kokkos.cpp \
../lammps-dev/src/KOKKOS/angle_class2_kokkos.cpp \
../lammps-dev/src/KOKKOS/angle_cosine_kokkos.cpp \
../lammps-dev/src/KOKKOS/angle_harmonic_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_angle_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_atomic_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_bond_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_charge_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_dpd_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_full_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_hybrid_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_molecular_kokkos.cpp \
../lammps-dev/src/KOKKOS/atom_vec_sphere_kokkos.cpp \
../lammps-dev/src/KOKKOS/bond_class2_kokkos.cpp \
../lammps-dev/src/KOKKOS/bond_fene_kokkos.cpp \
../lammps-dev/src/KOKKOS/bond_harmonic_kokkos.cpp \
../lammps-dev/src/KOKKOS/comm_kokkos.cpp \
../lammps-dev/src/KOKKOS/comm_tiled_kokkos.cpp \
../lammps-dev/src/KOKKOS/compute_coord_atom_kokkos.cpp \
../lammps-dev/src/KOKKOS/compute_orientorder_atom_kokkos.cpp \
../lammps-dev/src/KOKKOS/compute_temp_kokkos.cpp \
../lammps-dev/src/KOKKOS/dihedral_charmm_kokkos.cpp \
../lammps-dev/src/KOKKOS/dihedral_class2_kokkos.cpp \
../lammps-dev/src/KOKKOS/dihedral_harmonic_kokkos.cpp \
../lammps-dev/src/KOKKOS/dihedral_opls_kokkos.cpp \
../lammps-dev/src/KOKKOS/domain_kokkos.cpp \
../lammps-dev/src/KOKKOS/fft3d_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_deform_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_dpd_energy_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_enforce2d_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_eos_table_rx_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_freeze_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_gravity_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_langevin_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_minimize_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_momentum_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_neigh_history_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_nh_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_nph_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_npt_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_nve_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_nve_sphere_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_nvt_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_property_atom_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_qeq_reax_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_reaxc_bonds_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_reaxc_species_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_rx_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_setforce_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_shake_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_shardlow_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_wall_lj93_kokkos.cpp \
../lammps-dev/src/KOKKOS/fix_wall_reflect_kokkos.cpp \
../lammps-dev/src/KOKKOS/gridcomm_kokkos.cpp \
../lammps-dev/src/KOKKOS/improper_class2_kokkos.cpp \
../lammps-dev/src/KOKKOS/improper_harmonic_kokkos.cpp \
../lammps-dev/src/KOKKOS/kissfft_kokkos.cpp \
../lammps-dev/src/KOKKOS/kokkos.cpp \
../lammps-dev/src/KOKKOS/math_special_kokkos.cpp \
../lammps-dev/src/KOKKOS/min_cg_kokkos.cpp \
../lammps-dev/src/KOKKOS/min_kokkos.cpp \
../lammps-dev/src/KOKKOS/min_linesearch_kokkos.cpp \
../lammps-dev/src/KOKKOS/modify_kokkos.cpp \
../lammps-dev/src/KOKKOS/nbin_kokkos.cpp \
../lammps-dev/src/KOKKOS/nbin_ssa_kokkos.cpp \
../lammps-dev/src/KOKKOS/neigh_bond_kokkos.cpp \
../lammps-dev/src/KOKKOS/neigh_list_kokkos.cpp \
../lammps-dev/src/KOKKOS/neighbor_kokkos.cpp \
../lammps-dev/src/KOKKOS/npair_copy_kokkos.cpp \
../lammps-dev/src/KOKKOS/npair_halffull_kokkos.cpp \
../lammps-dev/src/KOKKOS/npair_kokkos.cpp \
../lammps-dev/src/KOKKOS/npair_skip_kokkos.cpp \
../lammps-dev/src/KOKKOS/npair_ssa_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_buck_coul_cut_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_buck_coul_long_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_buck_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_coul_cut_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_coul_debye_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_coul_dsf_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_coul_long_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_coul_wolf_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_dpd_fdt_energy_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_eam_alloy_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_eam_fs_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_eam_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_exp6_rx_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_gran_hooke_history_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_hybrid_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_hybrid_overlay_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_implicit_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_charmm_coul_long_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_class2_coul_cut_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_class2_coul_long_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_class2_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_cut_coul_cut_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_cut_coul_debye_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_cut_coul_dsf_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_cut_coul_long_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_cut_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_expand_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_gromacs_coul_gromacs_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_gromacs_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_lj_sdk_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_morse_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_multi_lucy_rx_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_reaxc_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_snap_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_sw_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_table_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_table_rx_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_tersoff_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_tersoff_mod_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_tersoff_zbl_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_vashishta_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_yukawa_kokkos.cpp \
../lammps-dev/src/KOKKOS/pair_zbl_kokkos.cpp \
../lammps-dev/src/KOKKOS/pppm_kokkos.cpp \
../lammps-dev/src/KOKKOS/rand_pool_wrap_kokkos.cpp \
../lammps-dev/src/KOKKOS/region_block_kokkos.cpp \
../lammps-dev/src/KOKKOS/remap_kokkos.cpp \
../lammps-dev/src/KOKKOS/verlet_kokkos.cpp 

OBJS += \
./lammps-dev/src/KOKKOS/angle_charmm_kokkos.o \
./lammps-dev/src/KOKKOS/angle_class2_kokkos.o \
./lammps-dev/src/KOKKOS/angle_cosine_kokkos.o \
./lammps-dev/src/KOKKOS/angle_harmonic_kokkos.o \
./lammps-dev/src/KOKKOS/atom_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_angle_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_atomic_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_bond_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_charge_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_dpd_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_full_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_hybrid_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_molecular_kokkos.o \
./lammps-dev/src/KOKKOS/atom_vec_sphere_kokkos.o \
./lammps-dev/src/KOKKOS/bond_class2_kokkos.o \
./lammps-dev/src/KOKKOS/bond_fene_kokkos.o \
./lammps-dev/src/KOKKOS/bond_harmonic_kokkos.o \
./lammps-dev/src/KOKKOS/comm_kokkos.o \
./lammps-dev/src/KOKKOS/comm_tiled_kokkos.o \
./lammps-dev/src/KOKKOS/compute_coord_atom_kokkos.o \
./lammps-dev/src/KOKKOS/compute_orientorder_atom_kokkos.o \
./lammps-dev/src/KOKKOS/compute_temp_kokkos.o \
./lammps-dev/src/KOKKOS/dihedral_charmm_kokkos.o \
./lammps-dev/src/KOKKOS/dihedral_class2_kokkos.o \
./lammps-dev/src/KOKKOS/dihedral_harmonic_kokkos.o \
./lammps-dev/src/KOKKOS/dihedral_opls_kokkos.o \
./lammps-dev/src/KOKKOS/domain_kokkos.o \
./lammps-dev/src/KOKKOS/fft3d_kokkos.o \
./lammps-dev/src/KOKKOS/fix_deform_kokkos.o \
./lammps-dev/src/KOKKOS/fix_dpd_energy_kokkos.o \
./lammps-dev/src/KOKKOS/fix_enforce2d_kokkos.o \
./lammps-dev/src/KOKKOS/fix_eos_table_rx_kokkos.o \
./lammps-dev/src/KOKKOS/fix_freeze_kokkos.o \
./lammps-dev/src/KOKKOS/fix_gravity_kokkos.o \
./lammps-dev/src/KOKKOS/fix_langevin_kokkos.o \
./lammps-dev/src/KOKKOS/fix_minimize_kokkos.o \
./lammps-dev/src/KOKKOS/fix_momentum_kokkos.o \
./lammps-dev/src/KOKKOS/fix_neigh_history_kokkos.o \
./lammps-dev/src/KOKKOS/fix_nh_kokkos.o \
./lammps-dev/src/KOKKOS/fix_nph_kokkos.o \
./lammps-dev/src/KOKKOS/fix_npt_kokkos.o \
./lammps-dev/src/KOKKOS/fix_nve_kokkos.o \
./lammps-dev/src/KOKKOS/fix_nve_sphere_kokkos.o \
./lammps-dev/src/KOKKOS/fix_nvt_kokkos.o \
./lammps-dev/src/KOKKOS/fix_property_atom_kokkos.o \
./lammps-dev/src/KOKKOS/fix_qeq_reax_kokkos.o \
./lammps-dev/src/KOKKOS/fix_reaxc_bonds_kokkos.o \
./lammps-dev/src/KOKKOS/fix_reaxc_species_kokkos.o \
./lammps-dev/src/KOKKOS/fix_rx_kokkos.o \
./lammps-dev/src/KOKKOS/fix_setforce_kokkos.o \
./lammps-dev/src/KOKKOS/fix_shake_kokkos.o \
./lammps-dev/src/KOKKOS/fix_shardlow_kokkos.o \
./lammps-dev/src/KOKKOS/fix_wall_lj93_kokkos.o \
./lammps-dev/src/KOKKOS/fix_wall_reflect_kokkos.o \
./lammps-dev/src/KOKKOS/gridcomm_kokkos.o \
./lammps-dev/src/KOKKOS/improper_class2_kokkos.o \
./lammps-dev/src/KOKKOS/improper_harmonic_kokkos.o \
./lammps-dev/src/KOKKOS/kissfft_kokkos.o \
./lammps-dev/src/KOKKOS/kokkos.o \
./lammps-dev/src/KOKKOS/math_special_kokkos.o \
./lammps-dev/src/KOKKOS/min_cg_kokkos.o \
./lammps-dev/src/KOKKOS/min_kokkos.o \
./lammps-dev/src/KOKKOS/min_linesearch_kokkos.o \
./lammps-dev/src/KOKKOS/modify_kokkos.o \
./lammps-dev/src/KOKKOS/nbin_kokkos.o \
./lammps-dev/src/KOKKOS/nbin_ssa_kokkos.o \
./lammps-dev/src/KOKKOS/neigh_bond_kokkos.o \
./lammps-dev/src/KOKKOS/neigh_list_kokkos.o \
./lammps-dev/src/KOKKOS/neighbor_kokkos.o \
./lammps-dev/src/KOKKOS/npair_copy_kokkos.o \
./lammps-dev/src/KOKKOS/npair_halffull_kokkos.o \
./lammps-dev/src/KOKKOS/npair_kokkos.o \
./lammps-dev/src/KOKKOS/npair_skip_kokkos.o \
./lammps-dev/src/KOKKOS/npair_ssa_kokkos.o \
./lammps-dev/src/KOKKOS/pair_buck_coul_cut_kokkos.o \
./lammps-dev/src/KOKKOS/pair_buck_coul_long_kokkos.o \
./lammps-dev/src/KOKKOS/pair_buck_kokkos.o \
./lammps-dev/src/KOKKOS/pair_coul_cut_kokkos.o \
./lammps-dev/src/KOKKOS/pair_coul_debye_kokkos.o \
./lammps-dev/src/KOKKOS/pair_coul_dsf_kokkos.o \
./lammps-dev/src/KOKKOS/pair_coul_long_kokkos.o \
./lammps-dev/src/KOKKOS/pair_coul_wolf_kokkos.o \
./lammps-dev/src/KOKKOS/pair_dpd_fdt_energy_kokkos.o \
./lammps-dev/src/KOKKOS/pair_eam_alloy_kokkos.o \
./lammps-dev/src/KOKKOS/pair_eam_fs_kokkos.o \
./lammps-dev/src/KOKKOS/pair_eam_kokkos.o \
./lammps-dev/src/KOKKOS/pair_exp6_rx_kokkos.o \
./lammps-dev/src/KOKKOS/pair_gran_hooke_history_kokkos.o \
./lammps-dev/src/KOKKOS/pair_hybrid_kokkos.o \
./lammps-dev/src/KOKKOS/pair_hybrid_overlay_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_implicit_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_long_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_class2_coul_cut_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_class2_coul_long_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_class2_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_cut_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_debye_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_dsf_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_long_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_cut_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_expand_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_gromacs_coul_gromacs_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_gromacs_kokkos.o \
./lammps-dev/src/KOKKOS/pair_lj_sdk_kokkos.o \
./lammps-dev/src/KOKKOS/pair_morse_kokkos.o \
./lammps-dev/src/KOKKOS/pair_multi_lucy_rx_kokkos.o \
./lammps-dev/src/KOKKOS/pair_reaxc_kokkos.o \
./lammps-dev/src/KOKKOS/pair_snap_kokkos.o \
./lammps-dev/src/KOKKOS/pair_sw_kokkos.o \
./lammps-dev/src/KOKKOS/pair_table_kokkos.o \
./lammps-dev/src/KOKKOS/pair_table_rx_kokkos.o \
./lammps-dev/src/KOKKOS/pair_tersoff_kokkos.o \
./lammps-dev/src/KOKKOS/pair_tersoff_mod_kokkos.o \
./lammps-dev/src/KOKKOS/pair_tersoff_zbl_kokkos.o \
./lammps-dev/src/KOKKOS/pair_vashishta_kokkos.o \
./lammps-dev/src/KOKKOS/pair_yukawa_kokkos.o \
./lammps-dev/src/KOKKOS/pair_zbl_kokkos.o \
./lammps-dev/src/KOKKOS/pppm_kokkos.o \
./lammps-dev/src/KOKKOS/rand_pool_wrap_kokkos.o \
./lammps-dev/src/KOKKOS/region_block_kokkos.o \
./lammps-dev/src/KOKKOS/remap_kokkos.o \
./lammps-dev/src/KOKKOS/verlet_kokkos.o 

CPP_DEPS += \
./lammps-dev/src/KOKKOS/angle_charmm_kokkos.d \
./lammps-dev/src/KOKKOS/angle_class2_kokkos.d \
./lammps-dev/src/KOKKOS/angle_cosine_kokkos.d \
./lammps-dev/src/KOKKOS/angle_harmonic_kokkos.d \
./lammps-dev/src/KOKKOS/atom_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_angle_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_atomic_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_bond_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_charge_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_dpd_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_full_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_hybrid_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_molecular_kokkos.d \
./lammps-dev/src/KOKKOS/atom_vec_sphere_kokkos.d \
./lammps-dev/src/KOKKOS/bond_class2_kokkos.d \
./lammps-dev/src/KOKKOS/bond_fene_kokkos.d \
./lammps-dev/src/KOKKOS/bond_harmonic_kokkos.d \
./lammps-dev/src/KOKKOS/comm_kokkos.d \
./lammps-dev/src/KOKKOS/comm_tiled_kokkos.d \
./lammps-dev/src/KOKKOS/compute_coord_atom_kokkos.d \
./lammps-dev/src/KOKKOS/compute_orientorder_atom_kokkos.d \
./lammps-dev/src/KOKKOS/compute_temp_kokkos.d \
./lammps-dev/src/KOKKOS/dihedral_charmm_kokkos.d \
./lammps-dev/src/KOKKOS/dihedral_class2_kokkos.d \
./lammps-dev/src/KOKKOS/dihedral_harmonic_kokkos.d \
./lammps-dev/src/KOKKOS/dihedral_opls_kokkos.d \
./lammps-dev/src/KOKKOS/domain_kokkos.d \
./lammps-dev/src/KOKKOS/fft3d_kokkos.d \
./lammps-dev/src/KOKKOS/fix_deform_kokkos.d \
./lammps-dev/src/KOKKOS/fix_dpd_energy_kokkos.d \
./lammps-dev/src/KOKKOS/fix_enforce2d_kokkos.d \
./lammps-dev/src/KOKKOS/fix_eos_table_rx_kokkos.d \
./lammps-dev/src/KOKKOS/fix_freeze_kokkos.d \
./lammps-dev/src/KOKKOS/fix_gravity_kokkos.d \
./lammps-dev/src/KOKKOS/fix_langevin_kokkos.d \
./lammps-dev/src/KOKKOS/fix_minimize_kokkos.d \
./lammps-dev/src/KOKKOS/fix_momentum_kokkos.d \
./lammps-dev/src/KOKKOS/fix_neigh_history_kokkos.d \
./lammps-dev/src/KOKKOS/fix_nh_kokkos.d \
./lammps-dev/src/KOKKOS/fix_nph_kokkos.d \
./lammps-dev/src/KOKKOS/fix_npt_kokkos.d \
./lammps-dev/src/KOKKOS/fix_nve_kokkos.d \
./lammps-dev/src/KOKKOS/fix_nve_sphere_kokkos.d \
./lammps-dev/src/KOKKOS/fix_nvt_kokkos.d \
./lammps-dev/src/KOKKOS/fix_property_atom_kokkos.d \
./lammps-dev/src/KOKKOS/fix_qeq_reax_kokkos.d \
./lammps-dev/src/KOKKOS/fix_reaxc_bonds_kokkos.d \
./lammps-dev/src/KOKKOS/fix_reaxc_species_kokkos.d \
./lammps-dev/src/KOKKOS/fix_rx_kokkos.d \
./lammps-dev/src/KOKKOS/fix_setforce_kokkos.d \
./lammps-dev/src/KOKKOS/fix_shake_kokkos.d \
./lammps-dev/src/KOKKOS/fix_shardlow_kokkos.d \
./lammps-dev/src/KOKKOS/fix_wall_lj93_kokkos.d \
./lammps-dev/src/KOKKOS/fix_wall_reflect_kokkos.d \
./lammps-dev/src/KOKKOS/gridcomm_kokkos.d \
./lammps-dev/src/KOKKOS/improper_class2_kokkos.d \
./lammps-dev/src/KOKKOS/improper_harmonic_kokkos.d \
./lammps-dev/src/KOKKOS/kissfft_kokkos.d \
./lammps-dev/src/KOKKOS/kokkos.d \
./lammps-dev/src/KOKKOS/math_special_kokkos.d \
./lammps-dev/src/KOKKOS/min_cg_kokkos.d \
./lammps-dev/src/KOKKOS/min_kokkos.d \
./lammps-dev/src/KOKKOS/min_linesearch_kokkos.d \
./lammps-dev/src/KOKKOS/modify_kokkos.d \
./lammps-dev/src/KOKKOS/nbin_kokkos.d \
./lammps-dev/src/KOKKOS/nbin_ssa_kokkos.d \
./lammps-dev/src/KOKKOS/neigh_bond_kokkos.d \
./lammps-dev/src/KOKKOS/neigh_list_kokkos.d \
./lammps-dev/src/KOKKOS/neighbor_kokkos.d \
./lammps-dev/src/KOKKOS/npair_copy_kokkos.d \
./lammps-dev/src/KOKKOS/npair_halffull_kokkos.d \
./lammps-dev/src/KOKKOS/npair_kokkos.d \
./lammps-dev/src/KOKKOS/npair_skip_kokkos.d \
./lammps-dev/src/KOKKOS/npair_ssa_kokkos.d \
./lammps-dev/src/KOKKOS/pair_buck_coul_cut_kokkos.d \
./lammps-dev/src/KOKKOS/pair_buck_coul_long_kokkos.d \
./lammps-dev/src/KOKKOS/pair_buck_kokkos.d \
./lammps-dev/src/KOKKOS/pair_coul_cut_kokkos.d \
./lammps-dev/src/KOKKOS/pair_coul_debye_kokkos.d \
./lammps-dev/src/KOKKOS/pair_coul_dsf_kokkos.d \
./lammps-dev/src/KOKKOS/pair_coul_long_kokkos.d \
./lammps-dev/src/KOKKOS/pair_coul_wolf_kokkos.d \
./lammps-dev/src/KOKKOS/pair_dpd_fdt_energy_kokkos.d \
./lammps-dev/src/KOKKOS/pair_eam_alloy_kokkos.d \
./lammps-dev/src/KOKKOS/pair_eam_fs_kokkos.d \
./lammps-dev/src/KOKKOS/pair_eam_kokkos.d \
./lammps-dev/src/KOKKOS/pair_exp6_rx_kokkos.d \
./lammps-dev/src/KOKKOS/pair_gran_hooke_history_kokkos.d \
./lammps-dev/src/KOKKOS/pair_hybrid_kokkos.d \
./lammps-dev/src/KOKKOS/pair_hybrid_overlay_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_implicit_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_charmm_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_charmm_coul_long_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_class2_coul_cut_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_class2_coul_long_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_class2_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_cut_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_debye_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_dsf_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_cut_coul_long_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_cut_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_expand_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_gromacs_coul_gromacs_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_gromacs_kokkos.d \
./lammps-dev/src/KOKKOS/pair_lj_sdk_kokkos.d \
./lammps-dev/src/KOKKOS/pair_morse_kokkos.d \
./lammps-dev/src/KOKKOS/pair_multi_lucy_rx_kokkos.d \
./lammps-dev/src/KOKKOS/pair_reaxc_kokkos.d \
./lammps-dev/src/KOKKOS/pair_snap_kokkos.d \
./lammps-dev/src/KOKKOS/pair_sw_kokkos.d \
./lammps-dev/src/KOKKOS/pair_table_kokkos.d \
./lammps-dev/src/KOKKOS/pair_table_rx_kokkos.d \
./lammps-dev/src/KOKKOS/pair_tersoff_kokkos.d \
./lammps-dev/src/KOKKOS/pair_tersoff_mod_kokkos.d \
./lammps-dev/src/KOKKOS/pair_tersoff_zbl_kokkos.d \
./lammps-dev/src/KOKKOS/pair_vashishta_kokkos.d \
./lammps-dev/src/KOKKOS/pair_yukawa_kokkos.d \
./lammps-dev/src/KOKKOS/pair_zbl_kokkos.d \
./lammps-dev/src/KOKKOS/pppm_kokkos.d \
./lammps-dev/src/KOKKOS/rand_pool_wrap_kokkos.d \
./lammps-dev/src/KOKKOS/region_block_kokkos.d \
./lammps-dev/src/KOKKOS/remap_kokkos.d \
./lammps-dev/src/KOKKOS/verlet_kokkos.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/src/KOKKOS/%.o: ../lammps-dev/src/KOKKOS/%.cpp lammps-dev/src/KOKKOS/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


