################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/lib/gpu/lal_answer.cpp \
../lammps-dev/lib/gpu/lal_atom.cpp \
../lammps-dev/lib/gpu/lal_base_atomic.cpp \
../lammps-dev/lib/gpu/lal_base_charge.cpp \
../lammps-dev/lib/gpu/lal_base_dipole.cpp \
../lammps-dev/lib/gpu/lal_base_dpd.cpp \
../lammps-dev/lib/gpu/lal_base_ellipsoid.cpp \
../lammps-dev/lib/gpu/lal_base_three.cpp \
../lammps-dev/lib/gpu/lal_beck.cpp \
../lammps-dev/lib/gpu/lal_beck_ext.cpp \
../lammps-dev/lib/gpu/lal_born.cpp \
../lammps-dev/lib/gpu/lal_born_coul_long.cpp \
../lammps-dev/lib/gpu/lal_born_coul_long_cs.cpp \
../lammps-dev/lib/gpu/lal_born_coul_long_cs_ext.cpp \
../lammps-dev/lib/gpu/lal_born_coul_long_ext.cpp \
../lammps-dev/lib/gpu/lal_born_coul_wolf.cpp \
../lammps-dev/lib/gpu/lal_born_coul_wolf_cs.cpp \
../lammps-dev/lib/gpu/lal_born_coul_wolf_cs_ext.cpp \
../lammps-dev/lib/gpu/lal_born_coul_wolf_ext.cpp \
../lammps-dev/lib/gpu/lal_born_ext.cpp \
../lammps-dev/lib/gpu/lal_buck.cpp \
../lammps-dev/lib/gpu/lal_buck_coul.cpp \
../lammps-dev/lib/gpu/lal_buck_coul_ext.cpp \
../lammps-dev/lib/gpu/lal_buck_coul_long.cpp \
../lammps-dev/lib/gpu/lal_buck_coul_long_ext.cpp \
../lammps-dev/lib/gpu/lal_buck_ext.cpp \
../lammps-dev/lib/gpu/lal_charmm_long.cpp \
../lammps-dev/lib/gpu/lal_charmm_long_ext.cpp \
../lammps-dev/lib/gpu/lal_colloid.cpp \
../lammps-dev/lib/gpu/lal_colloid_ext.cpp \
../lammps-dev/lib/gpu/lal_coul.cpp \
../lammps-dev/lib/gpu/lal_coul_debye.cpp \
../lammps-dev/lib/gpu/lal_coul_debye_ext.cpp \
../lammps-dev/lib/gpu/lal_coul_dsf.cpp \
../lammps-dev/lib/gpu/lal_coul_dsf_ext.cpp \
../lammps-dev/lib/gpu/lal_coul_ext.cpp \
../lammps-dev/lib/gpu/lal_coul_long.cpp \
../lammps-dev/lib/gpu/lal_coul_long_cs.cpp \
../lammps-dev/lib/gpu/lal_coul_long_cs_ext.cpp \
../lammps-dev/lib/gpu/lal_coul_long_ext.cpp \
../lammps-dev/lib/gpu/lal_device.cpp \
../lammps-dev/lib/gpu/lal_dipole_lj.cpp \
../lammps-dev/lib/gpu/lal_dipole_lj_ext.cpp \
../lammps-dev/lib/gpu/lal_dipole_lj_sf.cpp \
../lammps-dev/lib/gpu/lal_dipole_lj_sf_ext.cpp \
../lammps-dev/lib/gpu/lal_dipole_long_lj.cpp \
../lammps-dev/lib/gpu/lal_dipole_long_lj_ext.cpp \
../lammps-dev/lib/gpu/lal_dpd.cpp \
../lammps-dev/lib/gpu/lal_dpd_ext.cpp \
../lammps-dev/lib/gpu/lal_eam.cpp \
../lammps-dev/lib/gpu/lal_eam_alloy_ext.cpp \
../lammps-dev/lib/gpu/lal_eam_ext.cpp \
../lammps-dev/lib/gpu/lal_eam_fs_ext.cpp \
../lammps-dev/lib/gpu/lal_gauss.cpp \
../lammps-dev/lib/gpu/lal_gauss_ext.cpp \
../lammps-dev/lib/gpu/lal_gayberne.cpp \
../lammps-dev/lib/gpu/lal_gayberne_ext.cpp \
../lammps-dev/lib/gpu/lal_lj.cpp \
../lammps-dev/lib/gpu/lal_lj96.cpp \
../lammps-dev/lib/gpu/lal_lj96_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_class2_long.cpp \
../lammps-dev/lib/gpu/lal_lj_class2_long_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_coul.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_debye.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_debye_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_long.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_long_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_msm.cpp \
../lammps-dev/lib/gpu/lal_lj_coul_msm_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_cubic.cpp \
../lammps-dev/lib/gpu/lal_lj_cubic_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_dsf.cpp \
../lammps-dev/lib/gpu/lal_lj_dsf_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_expand.cpp \
../lammps-dev/lib/gpu/lal_lj_expand_coul_long.cpp \
../lammps-dev/lib/gpu/lal_lj_expand_coul_long_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_expand_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_gromacs.cpp \
../lammps-dev/lib/gpu/lal_lj_gromacs_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_sdk.cpp \
../lammps-dev/lib/gpu/lal_lj_sdk_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_sdk_long.cpp \
../lammps-dev/lib/gpu/lal_lj_sdk_long_ext.cpp \
../lammps-dev/lib/gpu/lal_lj_tip4p_long.cpp \
../lammps-dev/lib/gpu/lal_lj_tip4p_long_ext.cpp \
../lammps-dev/lib/gpu/lal_mie.cpp \
../lammps-dev/lib/gpu/lal_mie_ext.cpp \
../lammps-dev/lib/gpu/lal_morse.cpp \
../lammps-dev/lib/gpu/lal_morse_ext.cpp \
../lammps-dev/lib/gpu/lal_neighbor.cpp \
../lammps-dev/lib/gpu/lal_neighbor_shared.cpp \
../lammps-dev/lib/gpu/lal_pppm.cpp \
../lammps-dev/lib/gpu/lal_pppm_ext.cpp \
../lammps-dev/lib/gpu/lal_re_squared.cpp \
../lammps-dev/lib/gpu/lal_re_squared_ext.cpp \
../lammps-dev/lib/gpu/lal_soft.cpp \
../lammps-dev/lib/gpu/lal_soft_ext.cpp \
../lammps-dev/lib/gpu/lal_sw.cpp \
../lammps-dev/lib/gpu/lal_sw_ext.cpp \
../lammps-dev/lib/gpu/lal_table.cpp \
../lammps-dev/lib/gpu/lal_table_ext.cpp \
../lammps-dev/lib/gpu/lal_tersoff.cpp \
../lammps-dev/lib/gpu/lal_tersoff_ext.cpp \
../lammps-dev/lib/gpu/lal_tersoff_mod.cpp \
../lammps-dev/lib/gpu/lal_tersoff_mod_ext.cpp \
../lammps-dev/lib/gpu/lal_tersoff_zbl.cpp \
../lammps-dev/lib/gpu/lal_tersoff_zbl_ext.cpp \
../lammps-dev/lib/gpu/lal_ufm.cpp \
../lammps-dev/lib/gpu/lal_ufm_ext.cpp \
../lammps-dev/lib/gpu/lal_vashishta.cpp \
../lammps-dev/lib/gpu/lal_vashishta_ext.cpp \
../lammps-dev/lib/gpu/lal_yukawa.cpp \
../lammps-dev/lib/gpu/lal_yukawa_colloid.cpp \
../lammps-dev/lib/gpu/lal_yukawa_colloid_ext.cpp \
../lammps-dev/lib/gpu/lal_yukawa_ext.cpp \
../lammps-dev/lib/gpu/lal_zbl.cpp \
../lammps-dev/lib/gpu/lal_zbl_ext.cpp 

OBJS += \
./lammps-dev/lib/gpu/lal_answer.o \
./lammps-dev/lib/gpu/lal_atom.o \
./lammps-dev/lib/gpu/lal_base_atomic.o \
./lammps-dev/lib/gpu/lal_base_charge.o \
./lammps-dev/lib/gpu/lal_base_dipole.o \
./lammps-dev/lib/gpu/lal_base_dpd.o \
./lammps-dev/lib/gpu/lal_base_ellipsoid.o \
./lammps-dev/lib/gpu/lal_base_three.o \
./lammps-dev/lib/gpu/lal_beck.o \
./lammps-dev/lib/gpu/lal_beck_ext.o \
./lammps-dev/lib/gpu/lal_born.o \
./lammps-dev/lib/gpu/lal_born_coul_long.o \
./lammps-dev/lib/gpu/lal_born_coul_long_cs.o \
./lammps-dev/lib/gpu/lal_born_coul_long_cs_ext.o \
./lammps-dev/lib/gpu/lal_born_coul_long_ext.o \
./lammps-dev/lib/gpu/lal_born_coul_wolf.o \
./lammps-dev/lib/gpu/lal_born_coul_wolf_cs.o \
./lammps-dev/lib/gpu/lal_born_coul_wolf_cs_ext.o \
./lammps-dev/lib/gpu/lal_born_coul_wolf_ext.o \
./lammps-dev/lib/gpu/lal_born_ext.o \
./lammps-dev/lib/gpu/lal_buck.o \
./lammps-dev/lib/gpu/lal_buck_coul.o \
./lammps-dev/lib/gpu/lal_buck_coul_ext.o \
./lammps-dev/lib/gpu/lal_buck_coul_long.o \
./lammps-dev/lib/gpu/lal_buck_coul_long_ext.o \
./lammps-dev/lib/gpu/lal_buck_ext.o \
./lammps-dev/lib/gpu/lal_charmm_long.o \
./lammps-dev/lib/gpu/lal_charmm_long_ext.o \
./lammps-dev/lib/gpu/lal_colloid.o \
./lammps-dev/lib/gpu/lal_colloid_ext.o \
./lammps-dev/lib/gpu/lal_coul.o \
./lammps-dev/lib/gpu/lal_coul_debye.o \
./lammps-dev/lib/gpu/lal_coul_debye_ext.o \
./lammps-dev/lib/gpu/lal_coul_dsf.o \
./lammps-dev/lib/gpu/lal_coul_dsf_ext.o \
./lammps-dev/lib/gpu/lal_coul_ext.o \
./lammps-dev/lib/gpu/lal_coul_long.o \
./lammps-dev/lib/gpu/lal_coul_long_cs.o \
./lammps-dev/lib/gpu/lal_coul_long_cs_ext.o \
./lammps-dev/lib/gpu/lal_coul_long_ext.o \
./lammps-dev/lib/gpu/lal_device.o \
./lammps-dev/lib/gpu/lal_dipole_lj.o \
./lammps-dev/lib/gpu/lal_dipole_lj_ext.o \
./lammps-dev/lib/gpu/lal_dipole_lj_sf.o \
./lammps-dev/lib/gpu/lal_dipole_lj_sf_ext.o \
./lammps-dev/lib/gpu/lal_dipole_long_lj.o \
./lammps-dev/lib/gpu/lal_dipole_long_lj_ext.o \
./lammps-dev/lib/gpu/lal_dpd.o \
./lammps-dev/lib/gpu/lal_dpd_ext.o \
./lammps-dev/lib/gpu/lal_eam.o \
./lammps-dev/lib/gpu/lal_eam_alloy_ext.o \
./lammps-dev/lib/gpu/lal_eam_ext.o \
./lammps-dev/lib/gpu/lal_eam_fs_ext.o \
./lammps-dev/lib/gpu/lal_gauss.o \
./lammps-dev/lib/gpu/lal_gauss_ext.o \
./lammps-dev/lib/gpu/lal_gayberne.o \
./lammps-dev/lib/gpu/lal_gayberne_ext.o \
./lammps-dev/lib/gpu/lal_lj.o \
./lammps-dev/lib/gpu/lal_lj96.o \
./lammps-dev/lib/gpu/lal_lj96_ext.o \
./lammps-dev/lib/gpu/lal_lj_class2_long.o \
./lammps-dev/lib/gpu/lal_lj_class2_long_ext.o \
./lammps-dev/lib/gpu/lal_lj_coul.o \
./lammps-dev/lib/gpu/lal_lj_coul_debye.o \
./lammps-dev/lib/gpu/lal_lj_coul_debye_ext.o \
./lammps-dev/lib/gpu/lal_lj_coul_ext.o \
./lammps-dev/lib/gpu/lal_lj_coul_long.o \
./lammps-dev/lib/gpu/lal_lj_coul_long_ext.o \
./lammps-dev/lib/gpu/lal_lj_coul_msm.o \
./lammps-dev/lib/gpu/lal_lj_coul_msm_ext.o \
./lammps-dev/lib/gpu/lal_lj_cubic.o \
./lammps-dev/lib/gpu/lal_lj_cubic_ext.o \
./lammps-dev/lib/gpu/lal_lj_dsf.o \
./lammps-dev/lib/gpu/lal_lj_dsf_ext.o \
./lammps-dev/lib/gpu/lal_lj_expand.o \
./lammps-dev/lib/gpu/lal_lj_expand_coul_long.o \
./lammps-dev/lib/gpu/lal_lj_expand_coul_long_ext.o \
./lammps-dev/lib/gpu/lal_lj_expand_ext.o \
./lammps-dev/lib/gpu/lal_lj_ext.o \
./lammps-dev/lib/gpu/lal_lj_gromacs.o \
./lammps-dev/lib/gpu/lal_lj_gromacs_ext.o \
./lammps-dev/lib/gpu/lal_lj_sdk.o \
./lammps-dev/lib/gpu/lal_lj_sdk_ext.o \
./lammps-dev/lib/gpu/lal_lj_sdk_long.o \
./lammps-dev/lib/gpu/lal_lj_sdk_long_ext.o \
./lammps-dev/lib/gpu/lal_lj_tip4p_long.o \
./lammps-dev/lib/gpu/lal_lj_tip4p_long_ext.o \
./lammps-dev/lib/gpu/lal_mie.o \
./lammps-dev/lib/gpu/lal_mie_ext.o \
./lammps-dev/lib/gpu/lal_morse.o \
./lammps-dev/lib/gpu/lal_morse_ext.o \
./lammps-dev/lib/gpu/lal_neighbor.o \
./lammps-dev/lib/gpu/lal_neighbor_shared.o \
./lammps-dev/lib/gpu/lal_pppm.o \
./lammps-dev/lib/gpu/lal_pppm_ext.o \
./lammps-dev/lib/gpu/lal_re_squared.o \
./lammps-dev/lib/gpu/lal_re_squared_ext.o \
./lammps-dev/lib/gpu/lal_soft.o \
./lammps-dev/lib/gpu/lal_soft_ext.o \
./lammps-dev/lib/gpu/lal_sw.o \
./lammps-dev/lib/gpu/lal_sw_ext.o \
./lammps-dev/lib/gpu/lal_table.o \
./lammps-dev/lib/gpu/lal_table_ext.o \
./lammps-dev/lib/gpu/lal_tersoff.o \
./lammps-dev/lib/gpu/lal_tersoff_ext.o \
./lammps-dev/lib/gpu/lal_tersoff_mod.o \
./lammps-dev/lib/gpu/lal_tersoff_mod_ext.o \
./lammps-dev/lib/gpu/lal_tersoff_zbl.o \
./lammps-dev/lib/gpu/lal_tersoff_zbl_ext.o \
./lammps-dev/lib/gpu/lal_ufm.o \
./lammps-dev/lib/gpu/lal_ufm_ext.o \
./lammps-dev/lib/gpu/lal_vashishta.o \
./lammps-dev/lib/gpu/lal_vashishta_ext.o \
./lammps-dev/lib/gpu/lal_yukawa.o \
./lammps-dev/lib/gpu/lal_yukawa_colloid.o \
./lammps-dev/lib/gpu/lal_yukawa_colloid_ext.o \
./lammps-dev/lib/gpu/lal_yukawa_ext.o \
./lammps-dev/lib/gpu/lal_zbl.o \
./lammps-dev/lib/gpu/lal_zbl_ext.o 

CPP_DEPS += \
./lammps-dev/lib/gpu/lal_answer.d \
./lammps-dev/lib/gpu/lal_atom.d \
./lammps-dev/lib/gpu/lal_base_atomic.d \
./lammps-dev/lib/gpu/lal_base_charge.d \
./lammps-dev/lib/gpu/lal_base_dipole.d \
./lammps-dev/lib/gpu/lal_base_dpd.d \
./lammps-dev/lib/gpu/lal_base_ellipsoid.d \
./lammps-dev/lib/gpu/lal_base_three.d \
./lammps-dev/lib/gpu/lal_beck.d \
./lammps-dev/lib/gpu/lal_beck_ext.d \
./lammps-dev/lib/gpu/lal_born.d \
./lammps-dev/lib/gpu/lal_born_coul_long.d \
./lammps-dev/lib/gpu/lal_born_coul_long_cs.d \
./lammps-dev/lib/gpu/lal_born_coul_long_cs_ext.d \
./lammps-dev/lib/gpu/lal_born_coul_long_ext.d \
./lammps-dev/lib/gpu/lal_born_coul_wolf.d \
./lammps-dev/lib/gpu/lal_born_coul_wolf_cs.d \
./lammps-dev/lib/gpu/lal_born_coul_wolf_cs_ext.d \
./lammps-dev/lib/gpu/lal_born_coul_wolf_ext.d \
./lammps-dev/lib/gpu/lal_born_ext.d \
./lammps-dev/lib/gpu/lal_buck.d \
./lammps-dev/lib/gpu/lal_buck_coul.d \
./lammps-dev/lib/gpu/lal_buck_coul_ext.d \
./lammps-dev/lib/gpu/lal_buck_coul_long.d \
./lammps-dev/lib/gpu/lal_buck_coul_long_ext.d \
./lammps-dev/lib/gpu/lal_buck_ext.d \
./lammps-dev/lib/gpu/lal_charmm_long.d \
./lammps-dev/lib/gpu/lal_charmm_long_ext.d \
./lammps-dev/lib/gpu/lal_colloid.d \
./lammps-dev/lib/gpu/lal_colloid_ext.d \
./lammps-dev/lib/gpu/lal_coul.d \
./lammps-dev/lib/gpu/lal_coul_debye.d \
./lammps-dev/lib/gpu/lal_coul_debye_ext.d \
./lammps-dev/lib/gpu/lal_coul_dsf.d \
./lammps-dev/lib/gpu/lal_coul_dsf_ext.d \
./lammps-dev/lib/gpu/lal_coul_ext.d \
./lammps-dev/lib/gpu/lal_coul_long.d \
./lammps-dev/lib/gpu/lal_coul_long_cs.d \
./lammps-dev/lib/gpu/lal_coul_long_cs_ext.d \
./lammps-dev/lib/gpu/lal_coul_long_ext.d \
./lammps-dev/lib/gpu/lal_device.d \
./lammps-dev/lib/gpu/lal_dipole_lj.d \
./lammps-dev/lib/gpu/lal_dipole_lj_ext.d \
./lammps-dev/lib/gpu/lal_dipole_lj_sf.d \
./lammps-dev/lib/gpu/lal_dipole_lj_sf_ext.d \
./lammps-dev/lib/gpu/lal_dipole_long_lj.d \
./lammps-dev/lib/gpu/lal_dipole_long_lj_ext.d \
./lammps-dev/lib/gpu/lal_dpd.d \
./lammps-dev/lib/gpu/lal_dpd_ext.d \
./lammps-dev/lib/gpu/lal_eam.d \
./lammps-dev/lib/gpu/lal_eam_alloy_ext.d \
./lammps-dev/lib/gpu/lal_eam_ext.d \
./lammps-dev/lib/gpu/lal_eam_fs_ext.d \
./lammps-dev/lib/gpu/lal_gauss.d \
./lammps-dev/lib/gpu/lal_gauss_ext.d \
./lammps-dev/lib/gpu/lal_gayberne.d \
./lammps-dev/lib/gpu/lal_gayberne_ext.d \
./lammps-dev/lib/gpu/lal_lj.d \
./lammps-dev/lib/gpu/lal_lj96.d \
./lammps-dev/lib/gpu/lal_lj96_ext.d \
./lammps-dev/lib/gpu/lal_lj_class2_long.d \
./lammps-dev/lib/gpu/lal_lj_class2_long_ext.d \
./lammps-dev/lib/gpu/lal_lj_coul.d \
./lammps-dev/lib/gpu/lal_lj_coul_debye.d \
./lammps-dev/lib/gpu/lal_lj_coul_debye_ext.d \
./lammps-dev/lib/gpu/lal_lj_coul_ext.d \
./lammps-dev/lib/gpu/lal_lj_coul_long.d \
./lammps-dev/lib/gpu/lal_lj_coul_long_ext.d \
./lammps-dev/lib/gpu/lal_lj_coul_msm.d \
./lammps-dev/lib/gpu/lal_lj_coul_msm_ext.d \
./lammps-dev/lib/gpu/lal_lj_cubic.d \
./lammps-dev/lib/gpu/lal_lj_cubic_ext.d \
./lammps-dev/lib/gpu/lal_lj_dsf.d \
./lammps-dev/lib/gpu/lal_lj_dsf_ext.d \
./lammps-dev/lib/gpu/lal_lj_expand.d \
./lammps-dev/lib/gpu/lal_lj_expand_coul_long.d \
./lammps-dev/lib/gpu/lal_lj_expand_coul_long_ext.d \
./lammps-dev/lib/gpu/lal_lj_expand_ext.d \
./lammps-dev/lib/gpu/lal_lj_ext.d \
./lammps-dev/lib/gpu/lal_lj_gromacs.d \
./lammps-dev/lib/gpu/lal_lj_gromacs_ext.d \
./lammps-dev/lib/gpu/lal_lj_sdk.d \
./lammps-dev/lib/gpu/lal_lj_sdk_ext.d \
./lammps-dev/lib/gpu/lal_lj_sdk_long.d \
./lammps-dev/lib/gpu/lal_lj_sdk_long_ext.d \
./lammps-dev/lib/gpu/lal_lj_tip4p_long.d \
./lammps-dev/lib/gpu/lal_lj_tip4p_long_ext.d \
./lammps-dev/lib/gpu/lal_mie.d \
./lammps-dev/lib/gpu/lal_mie_ext.d \
./lammps-dev/lib/gpu/lal_morse.d \
./lammps-dev/lib/gpu/lal_morse_ext.d \
./lammps-dev/lib/gpu/lal_neighbor.d \
./lammps-dev/lib/gpu/lal_neighbor_shared.d \
./lammps-dev/lib/gpu/lal_pppm.d \
./lammps-dev/lib/gpu/lal_pppm_ext.d \
./lammps-dev/lib/gpu/lal_re_squared.d \
./lammps-dev/lib/gpu/lal_re_squared_ext.d \
./lammps-dev/lib/gpu/lal_soft.d \
./lammps-dev/lib/gpu/lal_soft_ext.d \
./lammps-dev/lib/gpu/lal_sw.d \
./lammps-dev/lib/gpu/lal_sw_ext.d \
./lammps-dev/lib/gpu/lal_table.d \
./lammps-dev/lib/gpu/lal_table_ext.d \
./lammps-dev/lib/gpu/lal_tersoff.d \
./lammps-dev/lib/gpu/lal_tersoff_ext.d \
./lammps-dev/lib/gpu/lal_tersoff_mod.d \
./lammps-dev/lib/gpu/lal_tersoff_mod_ext.d \
./lammps-dev/lib/gpu/lal_tersoff_zbl.d \
./lammps-dev/lib/gpu/lal_tersoff_zbl_ext.d \
./lammps-dev/lib/gpu/lal_ufm.d \
./lammps-dev/lib/gpu/lal_ufm_ext.d \
./lammps-dev/lib/gpu/lal_vashishta.d \
./lammps-dev/lib/gpu/lal_vashishta_ext.d \
./lammps-dev/lib/gpu/lal_yukawa.d \
./lammps-dev/lib/gpu/lal_yukawa_colloid.d \
./lammps-dev/lib/gpu/lal_yukawa_colloid_ext.d \
./lammps-dev/lib/gpu/lal_yukawa_ext.d \
./lammps-dev/lib/gpu/lal_zbl.d \
./lammps-dev/lib/gpu/lal_zbl_ext.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/lib/gpu/%.o: ../lammps-dev/lib/gpu/%.cpp lammps-dev/lib/gpu/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


