################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lammps-dev/src/USER-MISC/angle_cosine_shift.cpp \
../lammps-dev/src/USER-MISC/angle_cosine_shift_exp.cpp \
../lammps-dev/src/USER-MISC/angle_dipole.cpp \
../lammps-dev/src/USER-MISC/angle_fourier.cpp \
../lammps-dev/src/USER-MISC/angle_fourier_simple.cpp \
../lammps-dev/src/USER-MISC/angle_gaussian.cpp \
../lammps-dev/src/USER-MISC/angle_quartic.cpp \
../lammps-dev/src/USER-MISC/bond_gaussian.cpp \
../lammps-dev/src/USER-MISC/bond_harmonic_shift.cpp \
../lammps-dev/src/USER-MISC/bond_harmonic_shift_cut.cpp \
../lammps-dev/src/USER-MISC/bond_special.cpp \
../lammps-dev/src/USER-MISC/compute_ackland_atom.cpp \
../lammps-dev/src/USER-MISC/compute_basal_atom.cpp \
../lammps-dev/src/USER-MISC/compute_cnp_atom.cpp \
../lammps-dev/src/USER-MISC/compute_entropy_atom.cpp \
../lammps-dev/src/USER-MISC/compute_gyration_shape.cpp \
../lammps-dev/src/USER-MISC/compute_gyration_shape_chunk.cpp \
../lammps-dev/src/USER-MISC/compute_hma.cpp \
../lammps-dev/src/USER-MISC/compute_momentum.cpp \
../lammps-dev/src/USER-MISC/compute_pressure_cylinder.cpp \
../lammps-dev/src/USER-MISC/compute_pressure_grem.cpp \
../lammps-dev/src/USER-MISC/compute_stress_mop.cpp \
../lammps-dev/src/USER-MISC/compute_stress_mop_profile.cpp \
../lammps-dev/src/USER-MISC/compute_temp_rotate.cpp \
../lammps-dev/src/USER-MISC/compute_viscosity_cos.cpp \
../lammps-dev/src/USER-MISC/dihedral_cosine_shift_exp.cpp \
../lammps-dev/src/USER-MISC/dihedral_fourier.cpp \
../lammps-dev/src/USER-MISC/dihedral_nharmonic.cpp \
../lammps-dev/src/USER-MISC/dihedral_quadratic.cpp \
../lammps-dev/src/USER-MISC/dihedral_spherical.cpp \
../lammps-dev/src/USER-MISC/dihedral_table.cpp \
../lammps-dev/src/USER-MISC/dihedral_table_cut.cpp \
../lammps-dev/src/USER-MISC/fix_accelerate_cos.cpp \
../lammps-dev/src/USER-MISC/fix_addtorque.cpp \
../lammps-dev/src/USER-MISC/fix_ave_correlate_long.cpp \
../lammps-dev/src/USER-MISC/fix_bond_react.cpp \
../lammps-dev/src/USER-MISC/fix_electron_stopping.cpp \
../lammps-dev/src/USER-MISC/fix_electron_stopping_fit.cpp \
../lammps-dev/src/USER-MISC/fix_ffl.cpp \
../lammps-dev/src/USER-MISC/fix_filter_corotate.cpp \
../lammps-dev/src/USER-MISC/fix_flow_gauss.cpp \
../lammps-dev/src/USER-MISC/fix_gle.cpp \
../lammps-dev/src/USER-MISC/fix_grem.cpp \
../lammps-dev/src/USER-MISC/fix_imd.cpp \
../lammps-dev/src/USER-MISC/fix_ipi.cpp \
../lammps-dev/src/USER-MISC/fix_momentum_chunk.cpp \
../lammps-dev/src/USER-MISC/fix_npt_cauchy.cpp \
../lammps-dev/src/USER-MISC/fix_nvk.cpp \
../lammps-dev/src/USER-MISC/fix_orient_eco.cpp \
../lammps-dev/src/USER-MISC/fix_pafi.cpp \
../lammps-dev/src/USER-MISC/fix_pimd.cpp \
../lammps-dev/src/USER-MISC/fix_propel_self.cpp \
../lammps-dev/src/USER-MISC/fix_rhok.cpp \
../lammps-dev/src/USER-MISC/fix_smd.cpp \
../lammps-dev/src/USER-MISC/fix_srp.cpp \
../lammps-dev/src/USER-MISC/fix_ti_spring.cpp \
../lammps-dev/src/USER-MISC/fix_ttm_mod.cpp \
../lammps-dev/src/USER-MISC/fix_wall_ees.cpp \
../lammps-dev/src/USER-MISC/fix_wall_reflect_stochastic.cpp \
../lammps-dev/src/USER-MISC/fix_wall_region_ees.cpp \
../lammps-dev/src/USER-MISC/improper_cossq.cpp \
../lammps-dev/src/USER-MISC/improper_distance.cpp \
../lammps-dev/src/USER-MISC/improper_fourier.cpp \
../lammps-dev/src/USER-MISC/improper_ring.cpp \
../lammps-dev/src/USER-MISC/pair_agni.cpp \
../lammps-dev/src/USER-MISC/pair_buck_mdf.cpp \
../lammps-dev/src/USER-MISC/pair_cosine_squared.cpp \
../lammps-dev/src/USER-MISC/pair_coul_diel.cpp \
../lammps-dev/src/USER-MISC/pair_coul_shield.cpp \
../lammps-dev/src/USER-MISC/pair_coul_slater_cut.cpp \
../lammps-dev/src/USER-MISC/pair_coul_slater_long.cpp \
../lammps-dev/src/USER-MISC/pair_drip.cpp \
../lammps-dev/src/USER-MISC/pair_e3b.cpp \
../lammps-dev/src/USER-MISC/pair_edip.cpp \
../lammps-dev/src/USER-MISC/pair_edip_multi.cpp \
../lammps-dev/src/USER-MISC/pair_extep.cpp \
../lammps-dev/src/USER-MISC/pair_gauss_cut.cpp \
../lammps-dev/src/USER-MISC/pair_ilp_graphene_hbn.cpp \
../lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_full.cpp \
../lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_z.cpp \
../lammps-dev/src/USER-MISC/pair_lebedeva_z.cpp \
../lammps-dev/src/USER-MISC/pair_lennard_mdf.cpp \
../lammps-dev/src/USER-MISC/pair_list.cpp \
../lammps-dev/src/USER-MISC/pair_lj_expand_coul_long.cpp \
../lammps-dev/src/USER-MISC/pair_lj_mdf.cpp \
../lammps-dev/src/USER-MISC/pair_lj_sf_dipole_sf.cpp \
../lammps-dev/src/USER-MISC/pair_local_density.cpp \
../lammps-dev/src/USER-MISC/pair_meam_spline.cpp \
../lammps-dev/src/USER-MISC/pair_meam_sw_spline.cpp \
../lammps-dev/src/USER-MISC/pair_mesocnt.cpp \
../lammps-dev/src/USER-MISC/pair_momb.cpp \
../lammps-dev/src/USER-MISC/pair_morse_smooth_linear.cpp \
../lammps-dev/src/USER-MISC/pair_srp.cpp \
../lammps-dev/src/USER-MISC/pair_tersoff_table.cpp \
../lammps-dev/src/USER-MISC/pair_wf_cut.cpp \
../lammps-dev/src/USER-MISC/temper_grem.cpp \
../lammps-dev/src/USER-MISC/temper_npt.cpp 

OBJS += \
./lammps-dev/src/USER-MISC/angle_cosine_shift.o \
./lammps-dev/src/USER-MISC/angle_cosine_shift_exp.o \
./lammps-dev/src/USER-MISC/angle_dipole.o \
./lammps-dev/src/USER-MISC/angle_fourier.o \
./lammps-dev/src/USER-MISC/angle_fourier_simple.o \
./lammps-dev/src/USER-MISC/angle_gaussian.o \
./lammps-dev/src/USER-MISC/angle_quartic.o \
./lammps-dev/src/USER-MISC/bond_gaussian.o \
./lammps-dev/src/USER-MISC/bond_harmonic_shift.o \
./lammps-dev/src/USER-MISC/bond_harmonic_shift_cut.o \
./lammps-dev/src/USER-MISC/bond_special.o \
./lammps-dev/src/USER-MISC/compute_ackland_atom.o \
./lammps-dev/src/USER-MISC/compute_basal_atom.o \
./lammps-dev/src/USER-MISC/compute_cnp_atom.o \
./lammps-dev/src/USER-MISC/compute_entropy_atom.o \
./lammps-dev/src/USER-MISC/compute_gyration_shape.o \
./lammps-dev/src/USER-MISC/compute_gyration_shape_chunk.o \
./lammps-dev/src/USER-MISC/compute_hma.o \
./lammps-dev/src/USER-MISC/compute_momentum.o \
./lammps-dev/src/USER-MISC/compute_pressure_cylinder.o \
./lammps-dev/src/USER-MISC/compute_pressure_grem.o \
./lammps-dev/src/USER-MISC/compute_stress_mop.o \
./lammps-dev/src/USER-MISC/compute_stress_mop_profile.o \
./lammps-dev/src/USER-MISC/compute_temp_rotate.o \
./lammps-dev/src/USER-MISC/compute_viscosity_cos.o \
./lammps-dev/src/USER-MISC/dihedral_cosine_shift_exp.o \
./lammps-dev/src/USER-MISC/dihedral_fourier.o \
./lammps-dev/src/USER-MISC/dihedral_nharmonic.o \
./lammps-dev/src/USER-MISC/dihedral_quadratic.o \
./lammps-dev/src/USER-MISC/dihedral_spherical.o \
./lammps-dev/src/USER-MISC/dihedral_table.o \
./lammps-dev/src/USER-MISC/dihedral_table_cut.o \
./lammps-dev/src/USER-MISC/fix_accelerate_cos.o \
./lammps-dev/src/USER-MISC/fix_addtorque.o \
./lammps-dev/src/USER-MISC/fix_ave_correlate_long.o \
./lammps-dev/src/USER-MISC/fix_bond_react.o \
./lammps-dev/src/USER-MISC/fix_electron_stopping.o \
./lammps-dev/src/USER-MISC/fix_electron_stopping_fit.o \
./lammps-dev/src/USER-MISC/fix_ffl.o \
./lammps-dev/src/USER-MISC/fix_filter_corotate.o \
./lammps-dev/src/USER-MISC/fix_flow_gauss.o \
./lammps-dev/src/USER-MISC/fix_gle.o \
./lammps-dev/src/USER-MISC/fix_grem.o \
./lammps-dev/src/USER-MISC/fix_imd.o \
./lammps-dev/src/USER-MISC/fix_ipi.o \
./lammps-dev/src/USER-MISC/fix_momentum_chunk.o \
./lammps-dev/src/USER-MISC/fix_npt_cauchy.o \
./lammps-dev/src/USER-MISC/fix_nvk.o \
./lammps-dev/src/USER-MISC/fix_orient_eco.o \
./lammps-dev/src/USER-MISC/fix_pafi.o \
./lammps-dev/src/USER-MISC/fix_pimd.o \
./lammps-dev/src/USER-MISC/fix_propel_self.o \
./lammps-dev/src/USER-MISC/fix_rhok.o \
./lammps-dev/src/USER-MISC/fix_smd.o \
./lammps-dev/src/USER-MISC/fix_srp.o \
./lammps-dev/src/USER-MISC/fix_ti_spring.o \
./lammps-dev/src/USER-MISC/fix_ttm_mod.o \
./lammps-dev/src/USER-MISC/fix_wall_ees.o \
./lammps-dev/src/USER-MISC/fix_wall_reflect_stochastic.o \
./lammps-dev/src/USER-MISC/fix_wall_region_ees.o \
./lammps-dev/src/USER-MISC/improper_cossq.o \
./lammps-dev/src/USER-MISC/improper_distance.o \
./lammps-dev/src/USER-MISC/improper_fourier.o \
./lammps-dev/src/USER-MISC/improper_ring.o \
./lammps-dev/src/USER-MISC/pair_agni.o \
./lammps-dev/src/USER-MISC/pair_buck_mdf.o \
./lammps-dev/src/USER-MISC/pair_cosine_squared.o \
./lammps-dev/src/USER-MISC/pair_coul_diel.o \
./lammps-dev/src/USER-MISC/pair_coul_shield.o \
./lammps-dev/src/USER-MISC/pair_coul_slater_cut.o \
./lammps-dev/src/USER-MISC/pair_coul_slater_long.o \
./lammps-dev/src/USER-MISC/pair_drip.o \
./lammps-dev/src/USER-MISC/pair_e3b.o \
./lammps-dev/src/USER-MISC/pair_edip.o \
./lammps-dev/src/USER-MISC/pair_edip_multi.o \
./lammps-dev/src/USER-MISC/pair_extep.o \
./lammps-dev/src/USER-MISC/pair_gauss_cut.o \
./lammps-dev/src/USER-MISC/pair_ilp_graphene_hbn.o \
./lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_full.o \
./lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_z.o \
./lammps-dev/src/USER-MISC/pair_lebedeva_z.o \
./lammps-dev/src/USER-MISC/pair_lennard_mdf.o \
./lammps-dev/src/USER-MISC/pair_list.o \
./lammps-dev/src/USER-MISC/pair_lj_expand_coul_long.o \
./lammps-dev/src/USER-MISC/pair_lj_mdf.o \
./lammps-dev/src/USER-MISC/pair_lj_sf_dipole_sf.o \
./lammps-dev/src/USER-MISC/pair_local_density.o \
./lammps-dev/src/USER-MISC/pair_meam_spline.o \
./lammps-dev/src/USER-MISC/pair_meam_sw_spline.o \
./lammps-dev/src/USER-MISC/pair_mesocnt.o \
./lammps-dev/src/USER-MISC/pair_momb.o \
./lammps-dev/src/USER-MISC/pair_morse_smooth_linear.o \
./lammps-dev/src/USER-MISC/pair_srp.o \
./lammps-dev/src/USER-MISC/pair_tersoff_table.o \
./lammps-dev/src/USER-MISC/pair_wf_cut.o \
./lammps-dev/src/USER-MISC/temper_grem.o \
./lammps-dev/src/USER-MISC/temper_npt.o 

CPP_DEPS += \
./lammps-dev/src/USER-MISC/angle_cosine_shift.d \
./lammps-dev/src/USER-MISC/angle_cosine_shift_exp.d \
./lammps-dev/src/USER-MISC/angle_dipole.d \
./lammps-dev/src/USER-MISC/angle_fourier.d \
./lammps-dev/src/USER-MISC/angle_fourier_simple.d \
./lammps-dev/src/USER-MISC/angle_gaussian.d \
./lammps-dev/src/USER-MISC/angle_quartic.d \
./lammps-dev/src/USER-MISC/bond_gaussian.d \
./lammps-dev/src/USER-MISC/bond_harmonic_shift.d \
./lammps-dev/src/USER-MISC/bond_harmonic_shift_cut.d \
./lammps-dev/src/USER-MISC/bond_special.d \
./lammps-dev/src/USER-MISC/compute_ackland_atom.d \
./lammps-dev/src/USER-MISC/compute_basal_atom.d \
./lammps-dev/src/USER-MISC/compute_cnp_atom.d \
./lammps-dev/src/USER-MISC/compute_entropy_atom.d \
./lammps-dev/src/USER-MISC/compute_gyration_shape.d \
./lammps-dev/src/USER-MISC/compute_gyration_shape_chunk.d \
./lammps-dev/src/USER-MISC/compute_hma.d \
./lammps-dev/src/USER-MISC/compute_momentum.d \
./lammps-dev/src/USER-MISC/compute_pressure_cylinder.d \
./lammps-dev/src/USER-MISC/compute_pressure_grem.d \
./lammps-dev/src/USER-MISC/compute_stress_mop.d \
./lammps-dev/src/USER-MISC/compute_stress_mop_profile.d \
./lammps-dev/src/USER-MISC/compute_temp_rotate.d \
./lammps-dev/src/USER-MISC/compute_viscosity_cos.d \
./lammps-dev/src/USER-MISC/dihedral_cosine_shift_exp.d \
./lammps-dev/src/USER-MISC/dihedral_fourier.d \
./lammps-dev/src/USER-MISC/dihedral_nharmonic.d \
./lammps-dev/src/USER-MISC/dihedral_quadratic.d \
./lammps-dev/src/USER-MISC/dihedral_spherical.d \
./lammps-dev/src/USER-MISC/dihedral_table.d \
./lammps-dev/src/USER-MISC/dihedral_table_cut.d \
./lammps-dev/src/USER-MISC/fix_accelerate_cos.d \
./lammps-dev/src/USER-MISC/fix_addtorque.d \
./lammps-dev/src/USER-MISC/fix_ave_correlate_long.d \
./lammps-dev/src/USER-MISC/fix_bond_react.d \
./lammps-dev/src/USER-MISC/fix_electron_stopping.d \
./lammps-dev/src/USER-MISC/fix_electron_stopping_fit.d \
./lammps-dev/src/USER-MISC/fix_ffl.d \
./lammps-dev/src/USER-MISC/fix_filter_corotate.d \
./lammps-dev/src/USER-MISC/fix_flow_gauss.d \
./lammps-dev/src/USER-MISC/fix_gle.d \
./lammps-dev/src/USER-MISC/fix_grem.d \
./lammps-dev/src/USER-MISC/fix_imd.d \
./lammps-dev/src/USER-MISC/fix_ipi.d \
./lammps-dev/src/USER-MISC/fix_momentum_chunk.d \
./lammps-dev/src/USER-MISC/fix_npt_cauchy.d \
./lammps-dev/src/USER-MISC/fix_nvk.d \
./lammps-dev/src/USER-MISC/fix_orient_eco.d \
./lammps-dev/src/USER-MISC/fix_pafi.d \
./lammps-dev/src/USER-MISC/fix_pimd.d \
./lammps-dev/src/USER-MISC/fix_propel_self.d \
./lammps-dev/src/USER-MISC/fix_rhok.d \
./lammps-dev/src/USER-MISC/fix_smd.d \
./lammps-dev/src/USER-MISC/fix_srp.d \
./lammps-dev/src/USER-MISC/fix_ti_spring.d \
./lammps-dev/src/USER-MISC/fix_ttm_mod.d \
./lammps-dev/src/USER-MISC/fix_wall_ees.d \
./lammps-dev/src/USER-MISC/fix_wall_reflect_stochastic.d \
./lammps-dev/src/USER-MISC/fix_wall_region_ees.d \
./lammps-dev/src/USER-MISC/improper_cossq.d \
./lammps-dev/src/USER-MISC/improper_distance.d \
./lammps-dev/src/USER-MISC/improper_fourier.d \
./lammps-dev/src/USER-MISC/improper_ring.d \
./lammps-dev/src/USER-MISC/pair_agni.d \
./lammps-dev/src/USER-MISC/pair_buck_mdf.d \
./lammps-dev/src/USER-MISC/pair_cosine_squared.d \
./lammps-dev/src/USER-MISC/pair_coul_diel.d \
./lammps-dev/src/USER-MISC/pair_coul_shield.d \
./lammps-dev/src/USER-MISC/pair_coul_slater_cut.d \
./lammps-dev/src/USER-MISC/pair_coul_slater_long.d \
./lammps-dev/src/USER-MISC/pair_drip.d \
./lammps-dev/src/USER-MISC/pair_e3b.d \
./lammps-dev/src/USER-MISC/pair_edip.d \
./lammps-dev/src/USER-MISC/pair_edip_multi.d \
./lammps-dev/src/USER-MISC/pair_extep.d \
./lammps-dev/src/USER-MISC/pair_gauss_cut.d \
./lammps-dev/src/USER-MISC/pair_ilp_graphene_hbn.d \
./lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_full.d \
./lammps-dev/src/USER-MISC/pair_kolmogorov_crespi_z.d \
./lammps-dev/src/USER-MISC/pair_lebedeva_z.d \
./lammps-dev/src/USER-MISC/pair_lennard_mdf.d \
./lammps-dev/src/USER-MISC/pair_list.d \
./lammps-dev/src/USER-MISC/pair_lj_expand_coul_long.d \
./lammps-dev/src/USER-MISC/pair_lj_mdf.d \
./lammps-dev/src/USER-MISC/pair_lj_sf_dipole_sf.d \
./lammps-dev/src/USER-MISC/pair_local_density.d \
./lammps-dev/src/USER-MISC/pair_meam_spline.d \
./lammps-dev/src/USER-MISC/pair_meam_sw_spline.d \
./lammps-dev/src/USER-MISC/pair_mesocnt.d \
./lammps-dev/src/USER-MISC/pair_momb.d \
./lammps-dev/src/USER-MISC/pair_morse_smooth_linear.d \
./lammps-dev/src/USER-MISC/pair_srp.d \
./lammps-dev/src/USER-MISC/pair_tersoff_table.d \
./lammps-dev/src/USER-MISC/pair_wf_cut.d \
./lammps-dev/src/USER-MISC/temper_grem.d \
./lammps-dev/src/USER-MISC/temper_npt.d 


# Each subdirectory must supply rules for building sources it contributes
lammps-dev/src/USER-MISC/%.o: ../lammps-dev/src/USER-MISC/%.cpp lammps-dev/src/USER-MISC/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	mpic++ -I"/mnt/data/home/codes/eclipse-workdir/KPM_Cpp/include" -I/mnt/data/home/codes/libs/spectra/include -I/usr/include/x86_64-linux-gnu/mpich/ -I/usr/include -I/mnt/data/home/codes/libs/include -I/mnt/data/home/codes/libs/eigen-3.4.0 -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


